### ISSUE TITLE
cannot read from timed out object

### ISSUE THREAD

**Issue by Dobatymo** [cherrypy/cheroot#105]
**I'm submitting a ...**
- [X] bug report
- [ ] feature request
- [ ] question about the decisions made in the repository

**Describe the bug. What is the current behavior?**
I found this in my error logs
```
ENGINE socket.error 'cannot read from timed out object'
Traceback (most recent call last):
  File "C:\Program Files\Python35\lib\site-packages\cheroot\server.py", line 1214, in communicate
    req.respond()
  File "C:\Program Files\Python35\lib\site-packages\cheroot\server.py", line 1018, in respond
    self.server.gateway(self).respond()
  File "C:\Program Files\Python35\lib\site-packages\cheroot\wsgi.py", line 147, in respond
    self.write(chunk)
  File "C:\Program Files\Python35\lib\site-packages\cheroot\wsgi.py", line 226, in write
    self.req.ensure_headers_sent()
  File "C:\Program Files\Python35\lib\site-packages\cheroot\server.py", line 1065, in ensure_headers_sent
    self.send_headers()
  File "C:\Program Files\Python35\lib\site-packages\cheroot\server.py", line 1131, in send_headers
    self.rfile.read(remaining)
  File "C:\Program Files\Python35\lib\site-packages\cheroot\server.py", line 341, in read
    data = self.rfile.read(size)
  File "C:\Program Files\Python35\lib\_pyio.py", line 1000, in read
    return self._read_unlocked(size)
  File "C:\Program Files\Python35\lib\_pyio.py", line 1040, in _read_unlocked
    chunk = self.raw.read(wanted)
  File "C:\Program Files\Python35\lib\socket.py", line 573, in readinto
    raise OSError("cannot read from timed out object")
OSError: cannot read from timed out object
```

**To Reproduce**
I don't know.

**Expected behavior**
This exception should be handled gracefully.

**Environment**
- Cheroot version: 6.3.2.post0 (my log entry is 2 weeks old, but i don't think I updated since then...)
- Python version: Python 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)] on win32
- OS: Windows Server 2012 R2 x64

**Comment by webknjaz** [comment]
> **To Reproduce**
> I don't know.

We need a way to reproduce this. Probably it would be setting timeout to a very low value or adding sleep before read. 

I guess that the solution might be catching exception and logging that properly, but we need some way to ensure what the cause is.

Is this reproducible consistently for you? Have you tried establishing slow/trottled connection against your server/app to see what happens?

**Comment by Dobatymo** [comment]
Sorry, I just saw this popup in my log file **once** 2 weeks ago. I have several thousand requests per day, so this really must be some weird edge case. I just thought I report it because like you said catching and logging it properly would be better behaviour. My server config doesn't change anything related to timeout.

But I will try to debug it a little bit after the weekend probably.

**Comment by webknjaz** [comment]
Well, it's logged properly from my perspective. Only known cases with exceptions should omit logging exception itself, otherwise, it becomes undebuggable.

**Comment by Dobatymo** [comment]
I found that the exception is raised if a timeout is ignored somewhere.
```
s = socket.socket()
s.settimeout(1) # make sure the server does not response during this time
s.connect(("127.0.0.1", 8080))
s = socket.SocketIO(s, "r")
try:
    s.read(1000)
except socket.timeout:
    pass

s.read(1000)
```
`recv()` on socket raises socket.timeout each time. read on SocketIO object raises socket.timeout exception first, but then a OSError.

**Comment by mewalig** [comment]
similar to https://github.com/cherrypy/cherrypy/issues/1861

**Comment by shoaib-xo** [comment]
No solution/workaround till date?
