### ISSUE TITLE
cheroot on python 3.x is broken in MacPorts due to backports.functools.lru_cache missing

### ISSUE THREAD

**Issue by mrdomino** [cherrypy/cheroot#203]
❓ **I'm submitting a ...**
- [X] 🐞 bug report
- [ ] 🐣 feature request
- [X] ❓ question about the decisions made in the repository

🐞 **Describe the bug. What is the current behavior?**

cheroot on Python 3.x seems to be broken in MacPorts at the moment due to backports.functools_lru_cache only being packaged for Python 2.7 there. It seems based on inspection that their current general approach to backports is to only package them for versions where the functionality is missing. (FYI, I'm not connected with MacPorts; I just use it.)

❓ **What is the motivation / use case for changing the behavior?**

I'd hope to be able to install cheroot from MacPorts.

💡 **To Reproduce**
1. Run `port install py37-cheroot`
2. Create `foo.py` with contents:
```py
__requires__ = 'cheroot'
from pkg_resources import load_entry_point
```
3. Run `python foo.py`

(I first encountered this issue with [fava](https://github.com/beancount/fava); the above is an attempt to minimize the failing case. Importing cheroot directly from the console does not have this issue.)

💡 **Expected behavior**

The script completes successfully.

📋 **Details**

```
Traceback (most recent call last):
  File "foo.py", line 4, in <module>
    from pkg_resources import load_entry_point
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3241, in <module>
    @_call_aside
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3225, in _call_aside
    f(*args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3254, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'backports.functools_lru_cache' distribution was not found and is required by cheroot
```

📋 **Environment**
- Cheroot version: 6.5.4
- Python version: 3.7.3
- OS: OSX 10.14.5, MacPorts 2.5.4

📋 **Additional context**

It seems like the options for fixing this are:
1. cheroot makes its backports.functools.lru_cache dependency conditional on Python 2.7.
2. MacPorts provides py-backports and py-backports-functools_lru_cache for Python 3.x, and makes py-cheroot depend on them.
3. MacPorts adds a patch in its py-cheroot port to simulate option 1.

I'd imagined that option 1 would be most straightforward, but then I found #181, and it seems like there are some disadvantages to that approach that I wasn't aware of. So I'm mentioning this to see which approach we want to take.

**Comment by mrdomino** [comment]
On reflection, I think probably option 3 is fine; I'm proceeding with that for now.
