### ISSUE TITLE
Improve support for TLS 1.3 post-handshake auth

### ISSUE THREAD

**Issue by webknjaz** [cherrypy/cheroot#209]
❓ **I'm submitting a ...**
- [X] 🐞 bug report
- [ ] 🐣 feature request
- [ ] ❓ question about the decisions made in the repository

🐞 **Describe the bug. What is the current behavior?**

Failed TLS auth causes an exception happening after the TLS handshake if the client uses `post_handshake_auth` TLS extension. This happens when the server tries to read bytes with HTTP payload from the TCP connection (when starting to parse HTTP request). This code should also be protected by try/except wrapper.

❓ **What is the motivation / use case for changing the behavior?**

Make it work.

💡 **To Reproduce**

N/A

💡 **Expected behavior**

No traceback.

📋 **Details**

📋 **Environment**

- Cheroot version: master
- CherryPy version: master
- Python version: 3.7
- OS: N/A
- Browser: N/A

📋 **Additional context**

https://github.com/cherrypy/cherrypy/issues/1509#issuecomment-504750442
```python-traceback
2019-06-23 11:45:27,812::WARNING::[_cplogging:216] [23/Jun/2019:11:45:27] ENGINE socket.error 1
Traceback (most recent call last):
  File "C:\Users\Saf\Documents\GitHub\tests\py3\lib\site-packages\cheroot\server.py", line 1263, in communicate
    req.parse_request()
  File "C:\Users\Saf\Documents\GitHub\tests\py3\lib\site-packages\cheroot\server.py", line 719, in parse_request
    success = self.read_request_line()
  File "C:\Users\Saf\Documents\GitHub\tests\py3\lib\site-packages\cheroot\server.py", line 760, in read_request_line
    request_line = self.rfile.readline()
  File "C:\Users\Saf\Documents\GitHub\tests\py3\lib\site-packages\cheroot\server.py", line 302, in readline
    data = self.rfile.readline(256)
  File "C:\Users\Saf\AppData\Local\Programs\Python\Python37\Lib\_pyio.py", line 513, in readline
    b = self.read(nreadahead())
  File "C:\Users\Saf\AppData\Local\Programs\Python\Python37\Lib\_pyio.py", line 492, in nreadahead
    readahead = self.peek(1)
  File "C:\Users\Saf\AppData\Local\Programs\Python\Python37\Lib\_pyio.py", line 1076, in peek
    return self._peek_unlocked(size)
  File "C:\Users\Saf\AppData\Local\Programs\Python\Python37\Lib\_pyio.py", line 1083, in _peek_unlocked
    current = self.raw.read(to_read)
  File "C:\Users\Saf\AppData\Local\Programs\Python\Python37\Lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\Saf\AppData\Local\Programs\Python\Python37\Lib\ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\Saf\AppData\Local\Programs\Python\Python37\Lib\ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:2488)
```

cc @Safihre

**Comment by webknjaz** [comment]
Hey @mxii-ca, your TLS-foo is better than mine. Does my assessment of the problem sound right?

**Comment by mxii-ca** [comment]
The above traceback does not provide enough information to confirm or deny whether or not the error came from a post handshake authentication. Looking through the linked issue, the reproductions consist of either using a browser when CherryPy is using a self-signed cert, or the following script from urllib3: https://gist.github.com/a648d793c847aa3be2ff5186bb8c1dc7 I did not test it myself, but, from what I can see, the code (the script, CherryPy, PyOpenSSL/cryptography/cpython) never uses post handshake authentication.

From https://tools.ietf.org/html/rfc8446#section-4.6.2:
> When the client has sent the "post_handshake_auth" extension (see Section 4.2.6), a server MAY request client authentication at any time after the handshake has completed by sending a CertificateRequest message.

OpenSSL does not enable this extension by default. It can be enabled by calling `SSL_CTX_set_post_handshake_auth()` or `SSL_set_post_handshake_auth()`. Once enabled, OpenSSL does not automatically trigger authentication, `SSL_verify_client_post_handshake()` must be explicitly called.

----

In the browser self-signed cert case, it only affected some browsers, specific to the version. 

From: https://hg.mozilla.org/mozilla-central/file/bfbde1e7984a2c899776f6908eb0a849b3dc3b4d/security/nss/lib/ssl/ssl3con.c#l7817
> We must wait for the server's certificate to be authenticated before sending the client certificate in order to disclosing the client certificate to an attacker that does not have a valid cert for the domain we are connecting to.

Firefox will allow the handshake to complete before it has verified the server's certificate so long as the server is not requesting a client certificate. This is presumably done to speed up the connection and potentially also to prevent a new connection from having to be spun up when the user clicks the "proceed to insecure page" button. Once verification has been performed (and potentially the user does not click proceed), Firefox sends the alert message indicating the certificate error and terminates the connection. Since SSL exceptions are only propagated when an ssl method is called, the subsequent `read()` on the server ends up raising this exception.

As far as I can tell, TLS places no limitations on when an alert may be sent. Also of note, the alert protocol predates TLS 1.3.
https://tools.ietf.org/html/rfc8446#section-6
https://tools.ietf.org/html/rfc5246#section-7.2

----

Without further investigation, I do not know why the urllib3 case happens... the issue states that the switch from cryptography 2.4 to 2.5 is the cause (pyopenssl wraps cryptography's ffi interface to openssl), a quick look at it shows that it added support for openssl 1.1.1 which happens to be the version of openssl that added support for TLS 1.3... so it is potentially related to TLS 1.3 and thus likely unrelated to the browser issue

**Comment by webknjaz** [comment]
Thanks for the analysis! It's valuable to record such pointers in tickets even when there's no ultimate solution yet.

So now it looks like we need something similar to https://github.com/cherrypy/cheroot/blob/b6edd3a2ff579e3e6d8276b0a262fd7fbb54adce/cheroot/ssl/builtin.py#L286-L302 around https://github.com/cherrypy/cheroot/blob/b6edd3a2ff579e3e6d8276b0a262fd7fbb54adce/cheroot/server.py#L1259 to ignore such alerts...

**Comment by thezoggy** [comment]
its easy to reproduce this in sabnzbd with latest cherrypy/cheroot, if you try to go to webapp https://ip:port  it will throw the traceback with a self-signed cert.

```
2021-03-16 15:55:08,801::ERROR::[_cplogging:213] [16/Mar/2021:15:55:08] ENGINE Error in HTTPServer.serve
Traceback (most recent call last):
  File "cheroot\server.py", line 1810, in serve
  File "cheroot\connections.py", line 201, in run
  File "cheroot\connections.py", line 218, in _run
  File "cheroot\connections.py", line 272, in _from_server_socket
  File "cheroot\ssl\builtin.py", line 277, in wrap
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLError: [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:1123)
```

would be nice to just suppress this traceback

**Comment by webknjaz** [comment]
@thezoggy we're unable to debug third-party software. The reproducer would need to be Cheroot-based and have no dependencies on unrelated libraries.
