### ISSUE TITLE
cheroot-8.1.0 failed to be installed on CentOS 7

### ISSUE THREAD

**Issue by iredmail** [cherrypy/cheroot#236]
❓ **I'm submitting a ...**
- [X] 🐞 bug report

🐞 **Describe the bug. What is the current behavior?**

On fresh CentOS 7.7, install cheroot:

```
# easy_install-2.7 cheroot
Searching for cheroot
Reading https://pypi.python.org/simple/cheroot/
Best match: cheroot 8.1.0
Downloading https://files.pythonhosted.org/packages/a1/6c/899c7de9323e440f7eda28fead4a84bd0ae5a557e6ebf8f12270cc502043/cheroot-8.1.0.tar.gz#sha256=3ff64073efa35b39d5e107410f5c79664dc8c6c5990651e970740c80ab8878a8
Processing cheroot-8.1.0.tar.gz
Writing /tmp/easy_install-7t6Pby/cheroot-8.1.0/setup.cfg
Running cheroot-8.1.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-7t6Pby/cheroot-8.1.0/egg-dist-tmp-ZAQYCf
/usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'use_scm_version'
  warnings.warn(msg)
warning: install_lib: 'build/lib' does not exist -- no Python modules to install

zip_safe flag not set; analyzing archive contents...
Adding UNKNOWN 0.0.0 to easy-install.pth file

Installed /usr/lib/python2.7/site-packages/UNKNOWN-0.0.0-py2.7.egg
Skipping dependencies for UNKNOWN 0.0.0
```

Try to use it:

```
[root@c7 ~]# python
Python 2.7.5 (default, Aug  7 2019, 00:51:29) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux2
...
>>> import cheroot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named cheroot
```

📋 **Environment**
- Cheroot version: 8.0.0, 8.1.0
- Python version: 2.7.5
- OS: CentOS 7.7

**Comment by webknjaz** [comment]
`easy_install` is a decade-deprecated tool, don't use it. Use Pip instead. The new version relies on setuptools 34+.

**Comment by iredmail** [comment]
cheroot-7.0.0 failed to be compiled:

```
# easy_install-2.7 "cheroot==7.0.0"
Searching for cheroot==7.0.0
Reading https://pypi.python.org/simple/cheroot/
Best match: cheroot 7.0.0
Downloading https://files.pythonhosted.org/packages/8a/07/18c73c3064e6a429084b93ed05acd51d557235ef32b72e1545ec09f30f5b/cheroot-7.0.0.tar.gz#sha256=6168371ab9aaf574ac5f75675f244bbfebf990202bf75048065e9d675b9ae719
Processing cheroot-7.0.0.tar.gz
Writing /tmp/easy_install-YIt42B/cheroot-7.0.0/setup.cfg
Running cheroot-7.0.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-YIt42B/cheroot-7.0.0/egg-dist-tmp-PhfEss
Traceback (most recent call last):
  File "/usr/bin/easy_install-2.7", line 9, in <module>
    load_entry_point('setuptools==0.9.8', 'console_scripts', 'easy_install-2.7')()
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1992, in main
    with_ei_usage(lambda:
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1979, in with_ei_usage
    return f()
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1996, in <lambda>
    distclass=DistributionWithoutHelpCommands, **kw
  File "/usr/lib64/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 380, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 623, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 653, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 849, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1130, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1115, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 69, in run_setup
    lambda: execfile(
  File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 120, in run
    return func()
  File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 71, in <lambda>
    {'__file__':setup_script, '__name__':'__main__'}
  File "setup.py", line 123, in <module>
  File "setup.py", line 74, in read_configuration
  File "setup.py", line 50, in cfg_val_to_list
TypeError: descriptor 'strip' requires a 'str' object but received a 'unicode'
```

**Comment by webknjaz** [comment]
See the changelog.

**Comment by iredmail** [comment]
@webknjaz Thank you very much. :)
