### ISSUE TITLE
Intermittent error in teardown of wsgi_server fixture

### ISSUE THREAD

**Issue by jaraco** [cherrypy/cheroot#238]
In [this test](https://circleci.com/gh/cherrypy/cheroot/1716#tests/containers/1), I observe failures during teardown leading to failed CI runs:

```
― ERROR at teardown of test_Content_Length_out[/wrong_cl_unbuffered-200-I too] ―
[gw29] linux -- Python 3.6.1 /root/project/.tox/py36/bin/python

    @pytest.fixture(scope='module')
    def wsgi_server():
        """Set up and tear down a Cheroot WSGI server instance."""
>       for srv in cheroot_server(cheroot.wsgi.Server):

srv        = <cheroot.wsgi.Server object at 0x7f7183501320>

cheroot/testing.py:67: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
cheroot/testing.py:61: in cheroot_server
    httpserver.stop()  # destroy it
cheroot/server.py:2064: in stop
    self.requests.stop(self.shutdown_timeout)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <cheroot.workers.threadpool.ThreadPool object at 0x7f7183501518>
timeout = 0

    def stop(self, timeout=5):
        """Terminate all worker threads.
    
        Args:
            timeout (int): time to wait for threads to stop gracefully
        """
        # Must shut down threads here so the code that calls
        # this method can know when all threads are stopped.
        for worker in self._threads:
            self._queue.put(_SHUTDOWNREQUEST)
    
        # Don't join currentThread (when stop is called inside a request).
        current = threading.currentThread()
        if timeout is not None and timeout >= 0:
            endtime = time.time() + timeout
        while self._threads:
            worker = self._threads.pop()
            if worker is not current and worker.is_alive():
                try:
                    if timeout is None or timeout < 0:
                        worker.join()
                    else:
                        remaining_time = endtime - time.time()
                        if remaining_time > 0:
                            worker.join(remaining_time)
                        if worker.is_alive():
                            # We exhausted the timeout.
                            # Forcibly shut down the socket.
                            c = worker.conn
                            if c and not c.rfile.closed:
                                try:
>                                   c.socket.shutdown(socket.SHUT_RD)
E                                   OSError: [Errno 107] Transport endpoint is not connected

c          = <cheroot.server.HTTPConnection object at 0x7f718359da58>
current    = <_MainThread(MainThread, started 140125736597248)>
endtime    = 1570937005.8063483
remaining_time = -0.0005140304565429688
self       = <cheroot.workers.threadpool.ThreadPool object at 0x7f7183501518>
timeout    = 0
worker     = <WorkerThread(CP Server Thread-2, stopped 140125502588672)>

cheroot/workers/threadpool.py:280: OSError
----------------------------- Captured stderr call -----------------------------
ValueError('Response body exceeds the declared Content-Length.',)
--------------------------- Captured stderr teardown ---------------------------
Traceback (most recent call last):
  File "/root/project/cheroot/server.py", line 1280, in communicate
    req.respond()
  File "/root/project/cheroot/server.py", line 1083, in respond
    self.server.gateway(self).respond()
  File "/root/project/cheroot/wsgi.py", line 148, in respond
    self.write(chunk)
  File "/root/project/cheroot/wsgi.py", line 240, in write
    'Response body exceeds the declared Content-Length.',
ValueError: Response body exceeds the declared Content-Length.

                                                                  26% ██▋       

― ERROR at teardown of test_Content_Length_out[/wrong_cl_buffered-500-The requested resource returned more bytes than the declared Content-Length.] ―
[gw28] linux -- Python 3.6.1 /root/project/.tox/py36/bin/python

    @pytest.fixture(scope='module')
    def wsgi_server():
        """Set up and tear down a Cheroot WSGI server instance."""
>       for srv in cheroot_server(cheroot.wsgi.Server):

srv        = <cheroot.wsgi.Server object at 0x7fe8a9743320>

cheroot/testing.py:67: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
cheroot/testing.py:61: in cheroot_server
    httpserver.stop()  # destroy it
cheroot/server.py:2064: in stop
    self.requests.stop(self.shutdown_timeout)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <cheroot.workers.threadpool.ThreadPool object at 0x7fe8a9743518>
timeout = 0

    def stop(self, timeout=5):
        """Terminate all worker threads.
    
        Args:
            timeout (int): time to wait for threads to stop gracefully
        """
        # Must shut down threads here so the code that calls
        # this method can know when all threads are stopped.
        for worker in self._threads:
            self._queue.put(_SHUTDOWNREQUEST)
    
        # Don't join currentThread (when stop is called inside a request).
        current = threading.currentThread()
        if timeout is not None and timeout >= 0:
            endtime = time.time() + timeout
        while self._threads:
            worker = self._threads.pop()
            if worker is not current and worker.is_alive():
                try:
                    if timeout is None or timeout < 0:
                        worker.join()
                    else:
                        remaining_time = endtime - time.time()
                        if remaining_time > 0:
                            worker.join(remaining_time)
                        if worker.is_alive():
                            # We exhausted the timeout.
                            # Forcibly shut down the socket.
                            c = worker.conn
                            if c and not c.rfile.closed:
                                try:
>                                   c.socket.shutdown(socket.SHUT_RD)
E                                   OSError: [Errno 107] Transport endpoint is not connected

c          = <cheroot.server.HTTPConnection object at 0x7fe8a97dfa58>
current    = <_MainThread(MainThread, started 140637477525248)>
endtime    = 1570937005.8055036
remaining_time = -0.0004260540008544922
self       = <cheroot.workers.threadpool.ThreadPool object at 0x7fe8a9743518>
timeout    = 0
worker     = <WorkerThread(CP Server Thread-2, stopped 140637243598592)>

cheroot/workers/threadpool.py:280: OSError
----------------------------- Captured stderr call -----------------------------
ValueError('Response body exceeds the declared Content-Length.',)
--------------------------- Captured stderr teardown ---------------------------
Traceback (most recent call last):
  File "/root/project/cheroot/server.py", line 1280, in communicate
    req.respond()
  File "/root/project/cheroot/server.py", line 1083, in respond
    self.server.gateway(self).respond()
  File "/root/project/cheroot/wsgi.py", line 148, in respond
    self.write(chunk)
  File "/root/project/cheroot/wsgi.py", line 240, in write
    'Response body exceeds the declared Content-Length.',
ValueError: Response body exceeds the declared Content-Length.
```

**Comment by jaraco** [comment]
I see a similar intermittent error running tests on macOS:

```
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――― ERROR at teardown of test_readall_or_close[0] ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
[gw6] darwin -- Python 3.8.0 /Users/jaraco/code/public/cherrypy/cheroot/.tox/python/bin/python

    @pytest.fixture(scope='module')
    def wsgi_server():
        """Set up and tear down a Cheroot WSGI server instance."""
>       for srv in cheroot_server(cheroot.wsgi.Server):

srv        = <cheroot.wsgi.Server object at 0x10367b1f0>

cheroot/testing.py:67: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
cheroot/testing.py:61: in cheroot_server
    httpserver.stop()  # destroy it
cheroot/server.py:2064: in stop
    self.requests.stop(self.shutdown_timeout)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <cheroot.workers.threadpool.ThreadPool object at 0x10367bf40>, timeout = 0

    def stop(self, timeout=5):
        """Terminate all worker threads.
    
        Args:
            timeout (int): time to wait for threads to stop gracefully
        """
        # Must shut down threads here so the code that calls
        # this method can know when all threads are stopped.
        for worker in self._threads:
            self._queue.put(_SHUTDOWNREQUEST)
    
        # Don't join currentThread (when stop is called inside a request).
        current = threading.currentThread()
        if timeout is not None and timeout >= 0:
            endtime = time.time() + timeout
        while self._threads:
            worker = self._threads.pop()
            if worker is not current and worker.is_alive():
                try:
                    if timeout is None or timeout < 0:
                        worker.join()
                    else:
                        remaining_time = endtime - time.time()
                        if remaining_time > 0:
                            worker.join(remaining_time)
                        if worker.is_alive():
                            # We exhausted the timeout.
                            # Forcibly shut down the socket.
                            c = worker.conn
                            if c and not c.rfile.closed:
                                try:
>                                   c.socket.shutdown(socket.SHUT_RD)
E                                   OSError: [Errno 57] Socket is not connected

c          = <cheroot.server.HTTPConnection object at 0x10367b250>
current    = <_MainThread(MainThread, started 4460875072)>
endtime    = 1570974486.333907
remaining_time = -0.0003859996795654297
self       = <cheroot.workers.threadpool.ThreadPool object at 0x10367bf40>
timeout    = 0
worker     = <WorkerThread(CP Server Thread-7, stopped 123145598615552)>

cheroot/workers/threadpool.py:280: OSError
                                                                                                                                                            18% █▊        

―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――― ERROR at teardown of test_readall_or_close[1001] ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
[gw7] darwin -- Python 3.8.0 /Users/jaraco/code/public/cherrypy/cheroot/.tox/python/bin/python

    @pytest.fixture(scope='module')
    def wsgi_server():
        """Set up and tear down a Cheroot WSGI server instance."""
>       for srv in cheroot_server(cheroot.wsgi.Server):

srv        = <cheroot.wsgi.Server object at 0x1041531f0>

cheroot/testing.py:67: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
cheroot/testing.py:61: in cheroot_server
    httpserver.stop()  # destroy it
cheroot/server.py:2064: in stop
    self.requests.stop(self.shutdown_timeout)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <cheroot.workers.threadpool.ThreadPool object at 0x104153f10>, timeout = 0

    def stop(self, timeout=5):
        """Terminate all worker threads.
    
        Args:
            timeout (int): time to wait for threads to stop gracefully
        """
        # Must shut down threads here so the code that calls
        # this method can know when all threads are stopped.
        for worker in self._threads:
            self._queue.put(_SHUTDOWNREQUEST)
    
        # Don't join currentThread (when stop is called inside a request).
        current = threading.currentThread()
        if timeout is not None and timeout >= 0:
            endtime = time.time() + timeout
        while self._threads:
            worker = self._threads.pop()
            if worker is not current and worker.is_alive():
                try:
                    if timeout is None or timeout < 0:
                        worker.join()
                    else:
                        remaining_time = endtime - time.time()
                        if remaining_time > 0:
                            worker.join(remaining_time)
                        if worker.is_alive():
                            # We exhausted the timeout.
                            # Forcibly shut down the socket.
                            c = worker.conn
                            if c and not c.rfile.closed:
                                try:
>                                   c.socket.shutdown(socket.SHUT_RD)
E                                   OSError: [Errno 57] Socket is not connected

c          = <cheroot.server.HTTPConnection object at 0x104153be0>
current    = <_MainThread(MainThread, started 4370365760)>
endtime    = 1570974486.341564
remaining_time = -0.00019598007202148438
self       = <cheroot.workers.threadpool.ThreadPool object at 0x104153f10>
timeout    = 0
worker     = <WorkerThread(CP Server Thread-7, stopped 123145547935744)>

cheroot/workers/threadpool.py:280: OSError
------------------------------------------------------------------------- Captured stderr setup --------------------------------------------------------------------------
Exception ignored in: <socket.socket fd=16, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::1', 62513, 0, 0), raddr=('::1', 62498, 0, 0)>
Traceback (most recent call last):
  File "/Users/jaraco/code/public/cherrypy/cheroot/cheroot/test/test_conn.py", line 118, in testing_server
    wsgi_server.server_client = wsgi_server_client
ResourceWarning: unclosed <socket.socket fd=16, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::1', 62513, 0, 0), raddr=('::1', 62498, 0, 0)>
                                                     
```

**Comment by jaraco** [comment]
Running the [exact same tests again](https://circleci.com/gh/cherrypy/cheroot/1717#tests/containers/2), this time they pass on Python 3.6 and 3.7 but fail on Python 3.5, so clearly we're working with intermittent failures.

I suspect there's a race condition in how that fixture is torn down when there are multiple tests running concurrently.

To test this hypothesis, I disabled the concurrent tests.

```diff
diff --git a/pytest.ini b/pytest.ini
index a99783bf..c06979a8 100644
--- a/pytest.ini
+++ b/pytest.ini
@@ -1,6 +1,6 @@
 [pytest]
 norecursedirs = dist docs build .tox .eggs
-addopts = --durations=10 -v -rxXs -l -n auto --testmon --doctest-modules --ignore cheroot/ssl/pyopenssl.py --junitxml=junit-test-results.xml --cov=cheroot --cov-report term-missing:skip-covered --cov-report xml
+addopts = --durations=10 -v -rxXs -l --testmon --doctest-modules --ignore cheroot/ssl/pyopenssl.py --junitxml=junit-test-results.xml --cov=cheroot --cov-report term-missing:skip-covered --cov-report xml
 filterwarnings =
     error
 doctest_optionflags = ALLOW_UNICODE ELLIPSIS
```

I was able to run the tests 5-6 times without the error, but then the error occurred again.

```
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――― ERROR at teardown of test_No_CRLF[\r\n\n] ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

    @pytest.fixture(scope='module')
    def wsgi_server():
        """Set up and tear down a Cheroot WSGI server instance."""
>       for srv in cheroot_server(cheroot.wsgi.Server):

srv        = <cheroot.wsgi.Server object at 0x10c18b4f0>

cheroot/testing.py:67: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
cheroot/testing.py:61: in cheroot_server
    httpserver.stop()  # destroy it
cheroot/server.py:2064: in stop
    self.requests.stop(self.shutdown_timeout)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <cheroot.workers.threadpool.ThreadPool object at 0x10c1580a0>, timeout = 0

    def stop(self, timeout=5):
        """Terminate all worker threads.
    
        Args:
            timeout (int): time to wait for threads to stop gracefully
        """
        # Must shut down threads here so the code that calls
        # this method can know when all threads are stopped.
        for worker in self._threads:
            self._queue.put(_SHUTDOWNREQUEST)
    
        # Don't join currentThread (when stop is called inside a request).
        current = threading.currentThread()
        if timeout is not None and timeout >= 0:
            endtime = time.time() + timeout
        while self._threads:
            worker = self._threads.pop()
            if worker is not current and worker.is_alive():
                try:
                    if timeout is None or timeout < 0:
                        worker.join()
                    else:
                        remaining_time = endtime - time.time()
                        if remaining_time > 0:
                            worker.join(remaining_time)
                        if worker.is_alive():
                            # We exhausted the timeout.
                            # Forcibly shut down the socket.
                            c = worker.conn
                            if c and not c.rfile.closed:
                                try:
>                                   c.socket.shutdown(socket.SHUT_RD)
E                                   OSError: [Errno 57] Socket is not connected

c          = <cheroot.server.HTTPConnection object at 0x10c158580>
current    = <_MainThread(MainThread, started 4544933184)>
endtime    = 1570974904.817461
remaining_time = -0.0002758502960205078
self       = <cheroot.workers.threadpool.ThreadPool object at 0x10c1580a0>
timeout    = 0
worker     = <WorkerThread(CP Server Thread-2, stopped 123145598836736)>

cheroot/workers/threadpool.py:280: OSError
```

So that means the concurrent tests isn't the cause and may not even be a factor.
