### ISSUE TITLE
Tests fail to run at maint/8.0.x

### ISSUE THREAD

**Issue by jaraco** [cherrypy/cheroot#279]
Check out the code at maint/8.0.x, and the tests fail to run:

```
cheroot maint/8.0.x $ tox -r                                                                                                                                              
python recreate: /Users/jaraco/code/public/cherrypy/cheroot/.tox/python
python installdeps: setuptools>=31.0.1
python develop-inst: /Users/jaraco/code/public/cherrypy/cheroot
python installed: apipkg==1.5,attrs==19.3.0,certifi==2020.4.5.1,cffi==1.14.0,chardet==3.0.4,-e git+gh://cherrypy/cheroot@679bc266717de634a4ca8877a70deff12920c57e#egg=cheroot,codecov==2.0.15,colorama==0.4.3,coverage==4.5.3,cryptography==2.9,docopt==0.6.2,execnet==1.7.1,idna==2.9,jaraco.functools==3.0.0,more-itertools==8.2.0,packaging==20.3,pathtools==0.1.2,pluggy==0.13.1,py==1.8.1,pycparser==2.20,pyOpenSSL==19.1.0,pyparsing==2.4.7,pytest==5.4.1,pytest-cov==2.7.1,pytest-forked==1.1.3,pytest-mock==1.10.4,pytest-sugar==0.9.2,pytest-testmon==1.0.2,pytest-watch==4.2.0,pytest-xdist==1.31.0,requests==2.23.0,requests-unixsocket==0.2.0,six==1.14.0,termcolor==1.1.0,trustme==0.6.0,urllib3==1.25.8,watchdog==0.10.2,wcwidth==0.1.9
python run-test-pre: PYTHONHASHSEED='1827473805'
python run-test: commands[0] | pytest --testmon-off
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --testmon-off
  inifile: /Users/jaraco/code/public/cherrypy/cheroot/pytest.ini
  rootdir: /Users/jaraco/code/public/cherrypy/cheroot

ERROR: InvocationError for command /Users/jaraco/code/public/cherrypy/cheroot/.tox/python/bin/pytest --testmon-off (exited with code 4)
________________________________________________________________________________ summary _________________________________________________________________________________
ERROR:   python: commands failed

```

I don't know what `--testmon-off` is, but searching for that error, I found no results on a web search.

**Comment by jaraco** [comment]
Looks like [the command line option changed](https://testmon.org/new-in-testmon-100.html).

**Comment by jaraco** [comment]
After fixing that issue, another issue emerges:

```
cheroot maint/8.0.x $ tox -r                                                                                                                                              
python recreate: /Users/jaraco/code/public/cherrypy/cheroot/.tox/python
python installdeps: setuptools>=31.0.1
python develop-inst: /Users/jaraco/code/public/cherrypy/cheroot
python installed: apipkg==1.5,attrs==19.3.0,certifi==2020.4.5.1,cffi==1.14.0,chardet==3.0.4,-e git+gh://cherrypy/cheroot@679bc266717de634a4ca8877a70deff12920c57e#egg=cheroot,codecov==2.0.15,colorama==0.4.3,coverage==4.5.3,cryptography==2.9,docopt==0.6.2,execnet==1.7.1,idna==2.9,jaraco.functools==3.0.0,more-itertools==8.2.0,packaging==20.3,pathtools==0.1.2,pluggy==0.13.1,py==1.8.1,pycparser==2.20,pyOpenSSL==19.1.0,pyparsing==2.4.7,pytest==5.4.1,pytest-cov==2.7.1,pytest-forked==1.1.3,pytest-mock==1.10.4,pytest-sugar==0.9.2,pytest-testmon==0.9.19,pytest-watch==4.2.0,pytest-xdist==1.31.0,requests==2.23.0,requests-unixsocket==0.2.0,six==1.14.0,termcolor==1.1.0,trustme==0.6.0,urllib3==1.25.8,watchdog==0.10.2,wcwidth==0.1.9
python run-test-pre: PYTHONHASHSEED='1115522199'
python run-test: commands[0] | pytest --testmon-off
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/jaraco/code/public/cherrypy/cheroot/.tox/python/lib/python3.8/site-packages/_pytest/main.py", line 187, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/Users/jaraco/code/public/cherrypy/cheroot/.tox/python/lib/python3.8/site-packages/_pytest/config/__init__.py", line 820, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/Users/jaraco/code/public/cherrypy/cheroot/.tox/python/lib/python3.8/site-packages/pluggy/hooks.py", line 308, in call_historic
INTERNALERROR>     res = self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/Users/jaraco/code/public/cherrypy/cheroot/.tox/python/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/jaraco/code/public/cherrypy/cheroot/.tox/python/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/Users/jaraco/code/public/cherrypy/cheroot/.tox/python/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/Users/jaraco/code/public/cherrypy/cheroot/.tox/python/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/Users/jaraco/code/public/cherrypy/cheroot/.tox/python/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Users/jaraco/code/public/cherrypy/cheroot/.tox/python/lib/python3.8/site-packages/pytest_sugar.py", line 176, in pytest_configure
INTERNALERROR>     sugar_reporter = SugarTerminalReporter(standard_reporter)
INTERNALERROR>   File "/Users/jaraco/code/public/cherrypy/cheroot/.tox/python/lib/python3.8/site-packages/pytest_sugar.py", line 214, in __init__
INTERNALERROR>     self.writer = self._tw
INTERNALERROR> AttributeError: can't set attribute
ERROR: InvocationError for command /Users/jaraco/code/public/cherrypy/cheroot/.tox/python/bin/pytest --testmon-off (exited with code 3)
________________________________________________________________________________ summary _________________________________________________________________________________
ERROR:   python: commands failed

```

**Comment by jaraco** [comment]
Cherry-picking acdd75291acbeed261d915e786945ffd1b265fef seems to have addressed the second issue.

**Comment by jaraco** [comment]
I closed too soon. Tests are [still failing in CI](https://github.com/cherrypy/cheroot/runs/577822602).

**Comment by jaraco** [comment]
I think trying to run against 8.0.x may be too old. Too many things have changed since it was released. I've cherry-picked a few fixes, but now tests are failing on the nightly build.

**Comment by webknjaz** [comment]
@jaraco ignore the nightly build, please. In particular, it's affected by the patch to cpython that makes URL validation in `http.client` stricter causing abstract UNIX socket tests fail because they require forbidden `\x00` to operate. I think it's safe to `xfail` it for now.

**Comment by webknjaz** [comment]
https://github.com/cherrypy/cheroot/commit/45e1bbb07eb75d596cb6648df287ba0a8dc15010 fixes nightly.

**Comment by webknjaz** [comment]
I've cherry-picked a few more things on top. Some jobs still need fixing tho.

**Comment by webknjaz** [comment]
Alright, it's green now. I've also added a cron job for it.

**Comment by jaraco** [comment]
Thanks, so awesome! This will really help in troubleshooting issues with #277.
