### ISSUE TITLE
Tests hang when PIP_USE_FEATURE=2020-resolver

### ISSUE THREAD

**Issue by jaraco** [cherrypy/cheroot#335]
Originally reported at https://github.com/pypa/pip/issues/9011#issuecomment-727295776, enabling the 2020-resolver in pip reveals a problem with this project's dependencies.

The problem sometimes manifests as a hang due to the reported issue and other times reports a couple of conflicts:

```
cheroot pypa-9011 $ tox
WARNING: --use-feature=2020-resolver no longer has any effect, since it is now the default dependency resolver in pip. This will become an error in pip 21.0.
WARNING: --use-feature=2020-resolver no longer has any effect, since it is now the default dependency resolver in pip. This will become an error in pip 21.0.
python develop-inst-nodeps: /Users/jaraco/code/public/cherrypy/cheroot
python installed: WARNING: --use-feature=2020-resolver no longer has any effect, since it is now the default dependency resolver in pip. This will become an error in pip 21.0.,-e git+gh://cherrypy/cheroot@e8074e6c2e4a1c9e179d8d85e8ecbfaa5e63f20f#egg=cheroot
python run-test-pre: PYTHONHASHSEED='4047577887'
python run-test: commands[0] | pytest --testmon-off
ERROR: InvocationError for command could not find executable pytest
_____________________________________________________________ summary ______________________________________________________________
ERROR:   python: commands failed

cheroot pypa-9011 $ tox -r
python recreate: /Users/jaraco/code/public/cherrypy/cheroot/.tox/python
python: pip_version is pip@git+https://github.com/uranusjr/pip@resolvelib-dev
python installdeps: setuptools>=40.4.3, pip>=19.1, wheel
python develop-inst: /Users/jaraco/code/public/cherrypy/cheroot
ERROR: invocation failed (exit code 1), logfile: /Users/jaraco/code/public/cherrypy/cheroot/.tox/python/log/python-3.log
============================================================ log start =============================================================
WARNING: --use-feature=2020-resolver no longer has any effect, since it is now the default dependency resolver in pip. This will become an error in pip 21.0.
Obtaining file:///Users/jaraco/code/public/cherrypy/cheroot
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Collecting six>=1.11.0
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting more-itertools>=2.6
  Using cached more_itertools-8.6.0-py3-none-any.whl (45 kB)
Collecting jaraco.functools
  Using cached jaraco.functools-3.0.1-py3-none-any.whl (6.7 kB)
Collecting codecov==2.1.10
  Using cached codecov-2.1.10-py2.py3-none-any.whl (16 kB)
Collecting pytest-testmon<1.0.0
  Using cached pytest_testmon-0.9.19-py3-none-any.whl (12 kB)
  Using cached pytest_testmon-0.9.18-py3-none-any.whl (12 kB)
  Using cached pytest-testmon-0.9.16.tar.gz (28 kB)
  Using cached pytest_testmon-0.9.15-py3-none-any.whl (14 kB)
  Using cached pytest-testmon-0.9.14.tar.gz (30 kB)
  Using cached pytest-testmon-0.9.13.tar.gz (37 kB)
  Using cached pytest-testmon-0.9.12.tar.gz (37 kB)
  Using cached pytest-testmon-0.9.11.tar.gz (36 kB)
  Using cached pytest-testmon-0.9.10.tar.gz (36 kB)
  Using cached pytest-testmon-0.9.9.tar.gz (36 kB)
  Using cached pytest-testmon-0.9.8.tar.gz (35 kB)
  Using cached pytest-testmon-0.9.7.tar.gz (35 kB)
  Using cached pytest-testmon-0.9.6.tar.gz (32 kB)
  Using cached pytest-testmon-0.9.5.tar.gz (32 kB)
  Using cached pytest-testmon-0.9.4.tar.gz (31 kB)
  Using cached pytest-testmon-0.9.3.tar.gz (31 kB)
  Using cached pytest-testmon-0.9.0.tar.gz (31 kB)
  Using cached pytest-testmon-0.8.3.tar.gz (30 kB)
  Using cached pytest-testmon-0.8.2.tar.gz (14 kB)
  Using cached pytest-testmon-0.8.1.tar.gz (13 kB)
  Using cached pytest-testmon-0.8.0.tar.gz (13 kB)
  Using cached pytest-testmon-0.7.tar.gz (13 kB)
  Using cached pytest-testmon-0.6.tar.gz (12 kB)
  Using cached pytest-testmon-0.5.tar.gz (12 kB)
  Using cached pytest-testmon-0.4.9.tar.gz (12 kB)
INFO: pip is looking at multiple versions of this package to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of this package to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of this package to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of this package to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of this package to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of this package to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install cheroot, cheroot, cheroot, cheroot, cheroot, cheroot, cheroot, cheroot, cheroot, cheroot, cheroot, cheroot, cheroot, cheroot, cheroot, cheroot, cheroot, cheroot, cheroot, cheroot, cheroot, cheroot, cheroot, cheroot, cheroot, cheroot, cheroot, cheroot, cheroot, cheroot, cheroot[testing] 8.4.6.dev20+ge8074e6c, cheroot[testing] 8.4.6.dev20+ge8074e6c, cheroot[testing] 8.4.6.dev20+ge8074e6c, cheroot[testing] 8.4.6.dev20+ge8074e6c, cheroot[testing] 8.4.6.dev20+ge8074e6c, cheroot[testing] 8.4.6.dev20+ge8074e6c, cheroot[testing] 8.4.6.dev20+ge8074e6c, cheroot[testing] 8.4.6.dev20+ge8074e6c, cheroot[testing] 8.4.6.dev20+ge8074e6c, cheroot[testing] 8.4.6.dev20+ge8074e6c, cheroot[testing] 8.4.6.dev20+ge8074e6c, cheroot[testing] 8.4.6.dev20+ge8074e6c, cheroot[testing] 8.4.6.dev20+ge8074e6c, cheroot[testing] 8.4.6.dev20+ge8074e6c, cheroot[testing] 8.4.6.dev20+ge8074e6c, cheroot[testing] 8.4.6.dev20+ge8074e6c, cheroot[testing] 8.4.6.dev20+ge8074e6c, cheroot[testing] 8.4.6.dev20+ge8074e6c, cheroot[testing] 8.4.6.dev20+ge8074e6c, cheroot[testing] 8.4.6.dev20+ge8074e6c, cheroot[testing] 8.4.6.dev20+ge8074e6c, cheroot[testing] 8.4.6.dev20+ge8074e6c, cheroot[testing] 8.4.6.dev20+ge8074e6c, cheroot[testing] 8.4.6.dev20+ge8074e6c and cheroot[testing] 8.4.6.dev20+ge8074e6c because these package versions have conflicting dependencies.

The conflict is caused by:
    cheroot[testing] 8.4.6.dev20+ge8074e6c depends on coverage==5.3; python_version != "3.4" and extra == "testing"
    codecov 2.1.10 depends on coverage
    pytest-testmon 0.9.19 depends on coverage<5 and >=4
    cheroot[testing] 8.4.6.dev20+ge8074e6c depends on coverage==5.3; python_version != "3.4" and extra == "testing"
    codecov 2.1.10 depends on coverage
    pytest-testmon 0.9.18 depends on coverage<5 and >=4
    cheroot[testing] 8.4.6.dev20+ge8074e6c depends on coverage==5.3; python_version != "3.4" and extra == "testing"
    codecov 2.1.10 depends on coverage
    pytest-testmon 0.9.16 depends on coverage<5 and >=4
    cheroot[testing] 8.4.6.dev20+ge8074e6c depends on coverage==5.3; python_version != "3.4" and extra == "testing"
    codecov 2.1.10 depends on coverage
    pytest-testmon 0.9.15 depends on coverage<5 and >=4
    cheroot[testing] 8.4.6.dev20+ge8074e6c depends on coverage==5.3; python_version != "3.4" and extra == "testing"
    codecov 2.1.10 depends on coverage
    pytest-testmon 0.9.14 depends on coverage<5 and >=4
    cheroot[testing] 8.4.6.dev20+ge8074e6c depends on pytest>=4.6.6; extra == "testing"
    pytest-testmon 0.9.13 depends on pytest<4 and >=2.8.0
    cheroot[testing] 8.4.6.dev20+ge8074e6c depends on pytest>=4.6.6; extra == "testing"
    pytest-testmon 0.9.12 depends on pytest<4 and >=2.8.0
    cheroot[testing] 8.4.6.dev20+ge8074e6c depends on pytest>=4.6.6; extra == "testing"
    pytest-testmon 0.9.11 depends on pytest<4 and >=2.8.0
    cheroot[testing] 8.4.6.dev20+ge8074e6c depends on pytest>=4.6.6; extra == "testing"
    pytest-testmon 0.9.10 depends on pytest<4 and >=2.8.0
    cheroot[testing] 8.4.6.dev20+ge8074e6c depends on pytest>=4.6.6; extra == "testing"
    pytest-testmon 0.9.9 depends on pytest<4 and >=2.8.0
    cheroot[testing] 8.4.6.dev20+ge8074e6c depends on pytest>=4.6.6; extra == "testing"
    pytest-testmon 0.9.8 depends on pytest<4 and >=2.8.0
    cheroot[testing] 8.4.6.dev20+ge8074e6c depends on pytest>=4.6.6; extra == "testing"
    pytest-testmon 0.9.7 depends on pytest<4 and >=2.8.0
    cheroot[testing] 8.4.6.dev20+ge8074e6c depends on pytest>=4.6.6; extra == "testing"
    pytest-testmon 0.9.6 depends on pytest<4 and >=2.8.0
    cheroot[testing] 8.4.6.dev20+ge8074e6c depends on pytest>=4.6.6; extra == "testing"
    pytest-testmon 0.9.5 depends on pytest<4 and >=2.8.0
    cheroot[testing] 8.4.6.dev20+ge8074e6c depends on pytest>=4.6.6; extra == "testing"
    pytest-testmon 0.9.4 depends on pytest<3.1 and >=2.8.0
    cheroot[testing] 8.4.6.dev20+ge8074e6c depends on pytest>=4.6.6; extra == "testing"
    pytest-testmon 0.9.3 depends on pytest<3.1 and >=2.8.0
    cheroot[testing] 8.4.6.dev20+ge8074e6c depends on pytest>=4.6.6; extra == "testing"
    pytest-testmon 0.9.0 depends on pytest<3.1 and >=2.8.0
    cheroot[testing] 8.4.6.dev20+ge8074e6c depends on pytest>=4.6.6; extra == "testing"
    pytest-testmon 0.8.3 depends on pytest<3.1 and >=2.7.0
    cheroot[testing] 8.4.6.dev20+ge8074e6c depends on pytest>=4.6.6; extra == "testing"
    pytest-testmon 0.8.2 depends on pytest<3 and >=2.7.0
    cheroot[testing] 8.4.6.dev20+ge8074e6c depends on pytest>=4.6.6; extra == "testing"
    pytest-testmon 0.8.1 depends on pytest<3 and >=2.7.0
    cheroot[testing] 8.4.6.dev20+ge8074e6c depends on pytest>=4.6.6; extra == "testing"
    pytest-testmon 0.8.0 depends on pytest<2.9 and >=2.7.0
    cheroot[testing] 8.4.6.dev20+ge8074e6c depends on pytest>=4.6.6; extra == "testing"
    pytest-testmon 0.7 depends on pytest<2.9 and >=2.7.0
    cheroot[testing] 8.4.6.dev20+ge8074e6c depends on pytest>=4.6.6; extra == "testing"
    pytest-testmon 0.6 depends on pytest<2.9 and >=2.7.0
    cheroot[testing] 8.4.6.dev20+ge8074e6c depends on pytest>=4.6.6; extra == "testing"
    pytest-testmon 0.5 depends on pytest<2.9 and >=2.7.0
    cheroot[testing] 8.4.6.dev20+ge8074e6c depends on pytest>=4.6.6; extra == "testing"
    pytest-testmon 0.4.9 depends on pytest<2.9 and >=2.7.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

============================================================= log end ==============================================================
_____________________________________________________________ summary ______________________________________________________________
ERROR:   python: InvocationError for command /Users/jaraco/code/public/cherrypy/cheroot/.tox/python/bin/python -m pip install --exists-action w -e '/Users/jaraco/code/public/cherrypy/cheroot[testing]' (exited with code 1)
```

**Comment by jaraco** [comment]
I see that testmon is pinned to `<1`, but I don't know why.

**Comment by webknjaz** [comment]
The newer version has different CLI flags and I haven't had time to go through the compat

**Comment by webknjaz** [comment]
Interesting... I'm curious if RTD hangs for the same reason: https://readthedocs.org/projects/cheroot/builds/12339929/.

**Comment by jaraco** [comment]
> Interesting... I'm curious if RTD hangs for the same reason: https://readthedocs.org/projects/cheroot/builds/12339929/.

Indeed, running `tox -e build-docs` hangs in the pypa-9011 branch.

**Comment by webknjaz** [comment]
@jaraco  FWIW I've reproduced it locally by running the same commands as RTD does, in a clean venv, separate from the one in tox. It explodes inside of setuptools

```console
$ 3.9-venv/bin/python -m pip show setuptools           
Name: setuptools
Version: 41.0.1
Summary: Easily download, build, install, upgrade, and uninstall Python packages
Home-page: https://github.com/pypa/setuptools
Author: Python Packaging Authority
Author-email: distutils-sig@python.org
License: UNKNOWN
Location: ~/src/github/cherrypy/cheroot/3.9-venv/lib/python3.9/site-packages
Requires: 
Required-by: Sphinx
$ 3.9-venv/bin/python -m pip install --no-binary=:all: pytest-watch
Collecting pytest-watch
  Using cached pytest-watch-4.2.0.tar.gz (16 kB)
    ERROR: Command errored out with exit status 1:
     command: ~/src/github/cherrypy/cheroot/3.9-venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-mk25ltpv/pytest-watch_99bf59bed8144828a347779bc0936678/setup.py'"'"'; __file__='"'"'/tmp/pip-install-mk25ltpv/pytest-watch_99bf59bed8144828a347779bc0936678/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-1fvjagqv
         cwd: /tmp/pip-install-mk25ltpv/pytest-watch_99bf59bed8144828a347779bc0936678/
    Complete output (16 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "~/src/github/cherrypy/cheroot/3.9-venv/lib/python3.9/site-packages/setuptools/__init__.py", line 14, in <module>
        from setuptools.dist import Distribution, Feature
      File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
      File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
      File "~/src/github/cherrypy/cheroot/3.9-venv/lib/python3.9/site-packages/_virtualenv.py", line 89, in exec_module
        old(module)
      File "~/src/github/cherrypy/cheroot/3.9-venv/lib/python3.9/site-packages/setuptools/dist.py", line 24, in <module>
        from setuptools.depends import Require
      File "~/src/github/cherrypy/cheroot/3.9-venv/lib/python3.9/site-packages/setuptools/depends.py", line 7, in <module>
        from .py33compat import Bytecode
      File "~/src/github/cherrypy/cheroot/3.9-venv/lib/python3.9/site-packages/setuptools/py33compat.py", line 54, in <module>
        unescape = getattr(html, 'unescape', html_parser.HTMLParser().unescape)
    AttributeError: 'HTMLParser' object has no attribute 'unescape'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

But if I upgrade `setuptools` to the latest version, it succeeds. So it's clearly a setuptools bug but I have no idea why we haven't hit it before: that `pytest-watch-4.2.0.tar.gz` tarball is about 2 years old.

**Comment by webknjaz** [comment]
Oh, is it another "leaky pip isolation" instance?
