### ISSUE TITLE
Windows error 10022 kills threads

### ISSUE THREAD

**Issue by AdamaTheHutt** [cherrypy/cheroot#375]
❓ **I'm submitting a ...**
- [X] 🐞 bug report
- [ ] 🐣 feature request
- [ ] ❓ question about the decisions made in the repository

🐞 **Describe the bug. What is the current behavior?**
Sometimes when closing a connection, we get an error, probably because it's already closed or similar. This is addressed in https://github.com/cherrypy/cheroot/commit/384e6d035b45e687aacfcd39b2fe6c8e8ab92f62 , the problem is that in windows the error might instead be WSAEINVAL (10022), and that is not catched. 

❓ **What is the motivation / use case for changing the behavior?**
Because of this, in combination with, I think, the error seen in https://github.com/cherrypy/cheroot/issues/358 , we are eventually running out of threads, and the server stops responding completely.

💡 **To Reproduce**
Don't know how to reproduce, we get this error sporadically in production. All threads are typically gone in a few days or sometimes weeks.

💡 **Expected behavior**
I expect this error to be ignored, so that the thread keeps on running.

📋 **Details**
Also tried switching to pyopenssl, but the same error happened there too.

📋 **Environment**
- Cheroot version: 8.5.2
- CherryPy version: -
- Python version: 3.8.9
- OS: Microsoft Windows Server 2016 Datacenter, 10.0.14393
- Browser: [?]

📋 **Additional context**
A typical error:
```
 Exception in thread CP Server Thread-18: 
Traceback (most recent call last): 
  File "c:\py\lib\threading.py", line 917, in _bootstrap_inner 
    self.run() 
  File "c:\py\lib\site-packages\cheroot\workers\threadpool.py", line 130, in run 
    conn.close() 
  File "c:\py\lib\site-packages\cheroot\server.py", line 1360, in close 
    self._close_kernel_socket() 
  File "c:\py\lib\site-packages\cheroot\server.py", line 1483, in _close_kernel_socket 
    shutdown(socket.SHUT_RDWR)  # actually send a TCP FIN 
  File "c:\py\lib\ssl.py", line 1090, in shutdown 
    super().shutdown(how) 
OSError: [WinError 10022] An invalid argument was supplied
```
Then similar exceptions for thread after thread, until none are left.

In the references added in https://github.com/cherrypy/cheroot/commit/9f9de6569531ef2bb9a2af6e2757c0ab0a26d4fc there are several examples of dealing with error 10022 also, for example https://github.com/python/cpython/commit/83a2c28 .

**Comment by webknjaz** [comment]
Looks like this error code is sometimes exposed as `EINVAL` or `WSAEINVAL`:

* https://github.com/python/cpython/blob/19ca114/Modules/errnomodule.c#L146-L152
* https://github.com/python/cpython/blob/19ca114/Modules/errnomodule.c#L791-L793

So it seems like maybe it should be covered already. At least in some envs. But somebody needs to check a reproducer under a relevant env. One way to do this is to connect to a GHA worker using https://github.com/marketplace/actions/debugging-with-tmate.

**Comment by AzureIP** [comment]
Hi,
I experienced this error, too. What is the current state?

**Comment by webknjaz** [comment]
@liquidaty I thought #649 made it better. No?

**Comment by liquidaty** [comment]
> @liquidaty I thought #649 made it better. No?

I did too, but under certain conditions it appears that threads are still either dying or becoming unresponsive. Might be related to line 1291 of [cheroot/server.py](https://github.com/cherrypy/cheroot/blob/1391e717daf7a5c233c2713d82e6d7380cb5345a/cheroot/server.py):

```
            req.respond() # <== here
            if not req.close_connection:
                return True
```

don't suppose there is an easy way to spit out, at regular intervals, the number of active and healthy threads?

**Comment by liquidaty** [comment]
> @liquidaty I thought #649 made it better. No?

@webknjaz here's an example of an actual error log:

```
[14/Jan/2025:15:08:07] ENGINE A fatal exception happened. Setting the server interrupt flag to OSError(22, 'An invalid argument was supplied', None, 10022, None) and giving up.

Please, report this on the Cheroot tracker at <https://github.com/cherrypy/cheroot/issues/new/choose>, providing a full reproducer with as much context and details as possible.
Traceback (most recent call last):
  File "cheroot\workers\threadpool.py", line 119, in run
    self._process_connections_until_interrupted()
  File "cheroot\workers\threadpool.py", line 216, in _process_connections_until_interrupted
    conn.close()
  File "cheroot\server.py", line 1364, in close
    self._close_kernel_socket()
  File "cheroot\server.py", line 1484, in _close_kernel_socket
    shutdown(socket.SHUT_RDWR)  # actually send a TCP FIN
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "ssl.py", line 1353, in shutdown
OSError: [WinError 10022] An invalid argument was supplied
```

**Comment by webknjaz** [comment]
Thanks for the traceback! I'm not sure yet. However, I seem to recall having some unfinished improvement attempts in this area somewhere on my laptop. I'll try to remember and see if those might be related.

**Comment by liquidaty** [comment]
@webknjaz see updated comment above with verified fix to this bug.

Due to the challenges in reliably reproducing this bug, took many, many hours to test and verify! Sometimes we could replicate within 1 hr, but usually it took at least 8 hrs, so I can imagine it might not be easy for you to replicate  either. But, I hope this 2-line change (which we are now incorporating into a custom version of cheroot) is self-explanatory enough that you can be comfortable eyeballing and incorporate asap

**Comment by liquidaty** [comment]
thoughts anyone?

**Comment by webknjaz** [comment]
xref #736

**Comment by webknjaz** [comment]
I think we also need to do something about `exc.errno` vs. `exc.winerror`. In general, I'd like to find a way to start relying on the high-level exceptions instead of low level error codes since Windows has like a million of those, but they could be semantically reduced to something along the lines of https://github.com/cherrypy/cheroot/blob/088647e/cheroot/errors.py#L91C40-L91C77.

Should we just go for catching https://docs.python.org/3/library/exceptions.html#ConnectionError ?

P.S. That's a really old piece of code. `socket.error` has been `OSError` for ages, for example. I'm 99% sure it could be replaced with a `ConnectionError`.

**Comment by webknjaz** [comment]
@liquidaty could you log the exact type of what's in `e` in your test env? Maybe something like `f'{e=} {e!r}'`.

**Comment by liquidaty** [comment]
> I think we also need to do something about exc.errno vs. exc.winerror

A comprehensive solution might be to just go down the list at https://github.com/python/cpython/blob/main/PC/errmap.h and make sure all of the possible codes are handled; seems to me that most if not all cases could rely solely on exc.errno. In this particular case, I don't know enough about where that error might possibly come from, to have any opinion on whether you can simply have a single way to handle exc.errno 22 (on all platforms), or whether that might lead to mishandling on non-win platforms that would, for proper handling, require further inspection to check if it is winerror 10022

> Should we just go for catching https://docs.python.org/3/library/exceptions.html#ConnectionError ?

Looking at the errors that covers, I would guess that will be insufficient. At the least, I don't see it covering 10022 / 22

> could you log the exact type of what's in e in your test env? Maybe something like f'{e=} {e!r}'.

I can try, but it may take a while as I'll have to redeploy the un-patched version on a test box and then hit it for hrs on end until the exception eventually comes up

**Comment by webknjaz** [comment]
> redeploy the un-patched version

I imagine you could add logging right before your patch?

**Comment by liquidaty** [comment]
> I imagine you could add logging right before your patch?

yea that is a much smarter way...

**Comment by webknjaz** [comment]
In a few recent PRs, there's some work happening around re-raising various low-level errors/exceptions as subclasses of `ConnectionError`. It's currently scoped to `cheroot.ssl.pyopenssl` but it's probably not a bad idea to extend it to other layers in follow-ups.

---

@liquidaty were you able to log the trace to see where your error originates?
