### ISSUE TITLE
Tests hang on macOS

### ISSUE THREAD

**Issue by jaraco** [cherrypy/cheroot#56]
While running the tests on my macOS 10.13.1, Python 3.6.3, the tests got to this point and stalled:

```
...
 cheroot/test/test_conn.py::ConnectionCloseTests.test_Streaming_with_len_10 ✓       43% ████▍     
 cheroot/test/test_conn.py::ConnectionCloseTests.test_Streaming_with_len_11 ✓       45% ████▌     
 cheroot/test/test_conn.py::ConnectionCloseTests.test_readall_or_close ✓            47% ████▊     ^CERROR: KEYBOARDINTERRUPT
```

**Comment by jaraco** [comment]
If I run the test on its own, it completes, so it's interacting with other tests.

**Comment by jaraco** [comment]
When I run the tests with `tox -- -s`, I see the server is failing to start:

```
 cheroot/test/test_conn.py::ConnectionCloseTests.test_Streaming_with_len_10 ✓       43% ████▍     
 cheroot/test/test_conn.py::ConnectionCloseTests.test_Streaming_with_len_11 ✓       45% ████▌     
 cheroot/test/test_conn.py::ConnectionCloseTests.test_readall_or_close ✓            47% ████▊     Keyboard Interrupt: shutting down
Exception in thread Thread-12:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/jaraco/Dropbox/code/public/cheroot/cheroot/server.py", line 1424, in safe_start
    self.start()
  File "/Users/jaraco/Dropbox/code/public/cheroot/cheroot/server.py", line 1500, in start
    raise socket.error(msg)
OSError: No socket could be created -- (('127.0.0.1', 54583): [Errno 48] Address already in use)

```

**Comment by jaraco** [comment]
(notice the KeyboardInterrupt over on the right; That appears spontaneously)
