### ISSUE TITLE
SABnzbd client - ENGINE Error in HTTP server: shutting down

### ISSUE THREAD

**Issue by ZoltrixGFC** [cherrypy/cheroot#710]
❓ **I'm submitting a ...**
- [X] 🐞 bug report
- [ ] 🐣 feature request
- [ ] ❓ question about the decisions made in the repository

🐞 **Describe the bug. What is the current behavior?**

❓ **What is the motivation / use case for changing the behavior?**

💡 **To Reproduce**

Queue up downloads in the SABnzbd client, after a period of time the client will hang and stop responding.

💡 **Expected behavior**

📋 **Details**

📋 **Environment**

- Cheroot version: Unsure what version the latest SABnzbd client uses?
- CherryPy version: X.X.X (if applicable)
- Python version: 3.8.X
- OS: Windows 11 Enterprise

📋 **Additional context**

**Comment by Safihre** [comment]
cheroot==10.0.1
cherrypy==18.9.0

Python version we use is 3.12.3, not 3.8 :)

**Comment by ZoltrixGFC** [comment]
Just adding a more info.

It had been sitting idle for a while, then threw out the errors below and crashed.

```
2024-05-12 20:36:11,033::INFO::[postproc:138] Saving postproc queue
2024-05-12 20:36:11,033::INFO::[downloader:409] Post-processing finished, resuming download
2024-05-12 20:36:15,047::INFO::[nzbqueue:230] Saving queue
2024-05-12 20:36:15,049::INFO::[postproc:138] Saving postproc queue
2024-05-12 20:36:15,051::INFO::[notifier:157] Sending notification: SABnzbd - Queue finished (type=queue_done, job_cat=None)
2024-05-12 20:36:21,625::INFO::[_cplogging:213] [12/May/2024:20:36:21] ENGINE Client ('192.168.0.26', 58176) lost   peer dropped the TLS connection suddenly, during handshake: (8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')
2024-05-12 20:36:21,628::INFO::[_cplogging:213] [12/May/2024:20:36:21] ENGINE Client ('192.168.0.26', 58164) lost   peer dropped the TLS connection suddenly, during handshake: (8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')
2024-05-12 20:37:29,339::INFO::[database:208] [N/A] Moved job SABnzbd_nzo_2a1nfhb6 to archive
2024-05-12 21:10:33,102::INFO::[notifier:157] Sending notification: Error - [12/May/2024:21:10:33] ENGINE A fatal exception happened. Setting the server interrupt flag to OSError(22, 'An invalid argument was supplied', None, 10022, None) and giving up.

Please, report this on the Cheroot tracker at <https://github.com/cherrypy/cheroot/issues/new/choose>, providing a full reproducer with as much context and details as possible.
Traceback (most recent call last):
  File "cheroot\workers\threadpool.py", line 119, in run
  File "cheroot\workers\threadpool.py", line 216, in _process_connections_until_interrupted
  File "cheroot\server.py", line 1364, in close
  File "cheroot\server.py", line 1484, in _close_kernel_socket
  File "ssl.py", line 1291, in shutdown
OSError: [WinError 10022] An invalid argument was supplied
 (type=error, job_cat=None)
2024-05-12 21:10:33,102::CRITICAL::[_cplogging:213] [12/May/2024:21:10:33] ENGINE A fatal exception happened. Setting the server interrupt flag to OSError(22, 'An invalid argument was supplied', None, 10022, None) and giving up.

Please, report this on the Cheroot tracker at <https://github.com/cherrypy/cheroot/issues/new/choose>, providing a full reproducer with as much context and details as possible.
Traceback (most recent call last):
  File "cheroot\workers\threadpool.py", line 119, in run
  File "cheroot\workers\threadpool.py", line 216, in _process_connections_until_interrupted
  File "cheroot\server.py", line 1364, in close
  File "cheroot\server.py", line 1484, in _close_kernel_socket
  File "ssl.py", line 1291, in shutdown
OSError: [WinError 10022] An invalid argument was supplied

2024-05-12 21:10:33,250::ERROR::[_cplogging:213] [12/May/2024:21:10:33] ENGINE Error in HTTP server: shutting down
Traceback (most recent call last):
  File "cherrypy\process\servers.py", line 225, in _start_http_thread
  File "cheroot\server.py", line 1845, in start
  File "cheroot\server.py", line 1833, in serve
  File "threading.py", line 1073, in _bootstrap_inner
  File "cheroot\workers\threadpool.py", line 119, in run
  File "cheroot\workers\threadpool.py", line 216, in _process_connections_until_interrupted
  File "cheroot\server.py", line 1364, in close
  File "cheroot\server.py", line 1484, in _close_kernel_socket
  File "ssl.py", line 1291, in shutdown
OSError: [WinError 10022] An invalid argument was supplied

2024-05-12 21:10:33,250::INFO::[_cplogging:213] [12/May/2024:21:10:33] ENGINE Bus STOPPING
2024-05-12 21:10:33,354::INFO::[_cplogging:213] [12/May/2024:21:10:33] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('192.168.0.31', 10443)) shut down
2024-05-12 21:10:33,354::INFO::[_cplogging:213] [12/May/2024:21:10:33] ENGINE Bus STOPPED
2024-05-12 21:10:33,354::INFO::[_cplogging:213] [12/May/2024:21:10:33] ENGINE Bus EXITING
2024-05-12 21:10:33,354::INFO::[_cplogging:213] [12/May/2024:21:10:33] ENGINE Bus EXITED
```

**Comment by webknjaz** [comment]
Are you able to come up with a Cheroot-only reproducer / regression test that would run in our CI? I haven't used Windows for like a decade so can't test it locally but a CI failure can be inspected remotely, if the need be...

**Comment by webknjaz** [comment]
FWIW 10.0.1 contains some bugfixes that I thought should be backwards compatible. If 10.0.0 didn't fail, the regression is somewhere in the diff. Although, it's also possible that the problem existed before and got more evident with the patches around exception processing and logging..

**Comment by webknjaz** [comment]
dupe of #375?

**Comment by ZoltrixGFC** [comment]
Now starting to wonder if it was my reverse proxy causing the issue. I posted the following info on the SABnzbd thread:

In the errors I posted above, 192.168.0.26 is a docker host running nginx proxy. I had SSL enabled on SABnzbd running via the reverse proxy, and I noticed the SSL error listed above:

```
2024-05-12 20:36:21,625::INFO::[_cplogging:213] [12/May/2024:20:36:21] ENGINE Client ('192.168.0.26', 58176) lost   peer dropped the TLS connection suddenly, during handshake: (8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')
2024-05-12 20:36:21,628::INFO::[_cplogging:213] [12/May/2024:20:36:21] ENGINE Client ('192.168.0.26', 58164) lost   peer dropped the TLS connection suddenly, during handshake: (8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')
```

Last night I did a fresh install of SABnzbd, left SSL off, and set my other services to correct directly to SABnzbd (not via nginx), so far it has stayed up.

No idea if the reverse proxy could have been an issue at all?

**Comment by Safihre** [comment]
@webknjaz Seems indeed #375. 
This is not one that can just be caught like you implemented for the other problems?

**Comment by webknjaz** [comment]
That was my working theory and I started researching it by checking out what Python stdlib does. Though, I didn't get to test it. If someone wants to check out if such a patch would work, please do and report back.

P.S. This issue also claims hanging which is something I'd expect to be impossible in v10.0.1. So it'd be nice to unpack what it means actually..

**Comment by webknjaz** [comment]
> 2024-05-12 20:36:21,625::INFO::[_cplogging:213] [12/May/2024:20:36:21] ENGINE Client ('192.168.0.26', 58176) lost   peer dropped the TLS connection suddenly, during handshake: (8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')
> 2024-05-12 20:36:21,628::INFO::[_cplogging:213] [12/May/2024:20:36:21] ENGINE Client ('192.168.0.26', 58164) lost   peer dropped the TLS connection suddenly, during handshake: (8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')

I added these log entries in the last release to make it cleaner what's happening.. Hoping to improve the formatting later.

**Comment by webknjaz** [comment]
> No idea if the reverse proxy could have been an issue at all?

For that, I'd need to know how it's set up. The latest version shouldn't run out of threads and hang..

If you set it up to use plain http when connecting to the https port, it would obviously not work.

**Comment by dguilloryjr** [comment]
I have this issue happening on my device right now. I will post logs the next time it stops. I just turned on debug logging today...

**Comment by thezoggy** [comment]
seen a few others reporting this issue, so far it seems like its only been reported on windows since we upgraded cheroot from 10.0.0 to 10.0.1

**Comment by Safihre** [comment]
Since we got more complaints, I will 'fix' this for us by extending `errors.acceptable_sock_shutdown_exceptions` with `OSError`.
I (somewhat) understand you first want a reproducer before catching this, but I have end-users that I need to keep happy 😅

**Comment by AzureIP** [comment]
Is there a version that endusers like me can update to, to become happy again?

**Comment by Safihre** [comment]
Do you have the latest SABnzbd? Because it should catch those errors.

**Comment by AzureIP** [comment]
Sorry, I read not enougth. I don't use SABnzbd. My problem is more in the direction of issue 375, and only because someone asked if this is related, it does not mean it is really related.

**Comment by mwstowe** [comment]
I ran into this on Linux with cheroot 11.1.2 / CherryPy 18.10.0 / Python 3.13 fronting SABnzbd over HTTPS. Symptom: the web UI serves fine after a restart, then goes blank within a day while the backend keeps working, and a restart temporarily fixes it. The error log fills with:

```
Exception ignored in: <function IOBase.__del__ at ...>
Traceback (most recent call last):
  File ".../_pyio.py", line 424, in __del__
  File ".../_pyio.py", line 1326, in close
  File ".../_pyio.py", line 1287, in flush
  File ".../cheroot/makefile.py", line 32, in _flush_unlocked
    n = self.raw.write(bytes(self._write_buf))
  File ".../ssl.py", line 1234, in send
OSError: [Errno 9] Bad file descriptor
```

Root cause: `BufferedWriter._flush_unlocked` only guards `io.BlockingIOError`. When a TLS connection is torn down abruptly (client abort, timeout) and the buffered writer still holds bytes, the implicit flush during finalization (`IOBase.__del__` -> `close` -> `flush`) writes to an already-invalid fd and raises `OSError` (EBADF) — or `ValueError` ("I/O operation on closed file"). Because it escapes a finalizer, it taints the worker thread teardown path; workers die without being replaced and the thread pool drains over time, which is what produces the "server appears up but serves nothing" blank UI. This is consistent with the shutdown-path traceback originally reported here.

I opened #843 with a fix and regression tests: `_flush_unlocked` now catches `OSError`/`ValueError`, drops the unsendable buffered bytes (the connection is gone), and returns cleanly. The two new tests in `test_makefile.py` fail without the change and pass with it.

Happy to adjust the approach (e.g. narrowing which errnos are swallowed, or only doing so when invoked via finalization) if the maintainers prefer.
