### ISSUE TITLE
random failures when running test_conn with Python 3.13

### ISSUE THREAD

**Issue by kulikjak** [cherrypy/cheroot#734]
❓ **I'm submitting a ...**
- [X] 🐞 bug report
- [ ] 🐣 feature request
- [ ] ❓ question about the decisions made in the repository

🐞 **Describe the bug. What is the current behavior?**
And one more failure with Python 3.13: when running `cheroot/test/test_conn.py`, I am seeing one of the tests fail with the following error:
```python-traceback
E                   pytest.PytestUnraisableExceptionWarning: Exception ignored in: <function IOBase.__del__ at 0x1ffd0ae81cea20>
E                   
E                   Traceback (most recent call last):
E                     File "/usr/lib/python3.13/_pyio.py", line 418, in __del__
E                       self.close()
E                       ~~~~~~~~~~^^
E                     File "/usr/lib/python3.13/_pyio.py", line 1313, in close
E                       self.flush()
E                       ~~~~~~~~~~^^
E                     File "/usr/lib/python3.13/_pyio.py", line 1274, in flush
E                       self._flush_unlocked()
E                       ~~~~~~~~~~~~~~~~~~~~^^
E                     File "/scratch/userland-gate/components/python/cheroot/cheroot-10.0.0/cheroot/makefile.py", line 33, in _flush_unlocked
E                       n = self.raw.write(bytes(self._write_buf))
E                     File "/usr/lib/python3.13/socket.py", line 737, in write
E                       return self._sock.send(b)
E                              ~~~~~~~~~~~~~~~^^^
E                   OSError: [Errno 9] Bad file number
```
I saw the following three fail: `test_streaming_10[True]`, `test_keepalive[HTTP/1.0]`, `test_keepalive[HTTP/1.1]` with this error, although it's always just one for each run (and it seems random).

This again seems to be related to the following io change:
https://docs.python.org/3/whatsnew/3.13.html#io

I wasn't able to find a fix for this one.

💡 **To Reproduce**
Run the test suite with Python 3.13.0.

📋 **Details**
Full traceback:
```python-traceback
==================================== ERRORS ====================================
__________________ ERROR at setup of test_keepalive[HTTP/1.0] __________________

cls = <class '_pytest.runner.CallInfo'>
func = <function call_and_report.<locals>.<lambda> at 0x1fffe71a7c2020>
when = 'setup'
reraise = (<class '_pytest.outcomes.Exit'>, <class 'KeyboardInterrupt'>)

    @classmethod
    def from_call(
        cls,
        func: Callable[[], TResult],
        when: Literal["collect", "setup", "call", "teardown"],
        reraise: type[BaseException] | tuple[type[BaseException], ...] | None = None,
    ) -> CallInfo[TResult]:
        """Call func, wrapping the result in a CallInfo.
    
        :param func:
            The function to call. Called without arguments.
        :type func: Callable[[], _pytest.runner.TResult]
        :param when:
            The phase in which the function is called.
        :param reraise:
            Exception or exceptions that shall propagate if raised by the
            function, instead of being wrapped in the CallInfo.
        """
        excinfo = None
        start = timing.time()
        precise_start = timing.perf_counter()
        try:
>           result: TResult | None = func()

cls        = <class '_pytest.runner.CallInfo'>
duration   = 0.10653769504278898
excinfo    = <ExceptionInfo PytestUnraisableExceptionWarning('Exception ignored in: <function IOBase.__del__ at 0x1fffe71f1cea20>\n...in write\n    return self._sock.send(b)\n           ~~~~~~~~~~~~~~~^^^\nOSError: [Errno 9] Bad file number\n') tblen=8>
func       = <function call_and_report.<locals>.<lambda> at 0x1fffe71a7c2020>
precise_start = 7332079.8773448
precise_stop = 7332079.983882495
reraise    = (<class '_pytest.outcomes.Exit'>, <class 'KeyboardInterrupt'>)
result     = None
start      = 1730815279.3573403
stop       = 1730815279.463881
when       = 'setup'

/usr/lib/python3.13/vendor-packages/_pytest/runner.py:341: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/lib/python3.13/vendor-packages/_pytest/runner.py:242: in <lambda>
    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise
        item       = <Function test_keepalive[HTTP/1.0]>
        kwds       = {}
        runtest_hook = <HookCaller 'pytest_runtest_setup'>
/usr/lib/python3.13/vendor-packages/pluggy/_hooks.py:513: in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
        firstresult = False
        kwargs     = {'item': <Function test_keepalive[HTTP/1.0]>}
        self       = <HookCaller 'pytest_runtest_setup'>
/usr/lib/python3.13/vendor-packages/pluggy/_manager.py:120: in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
        firstresult = False
        hook_name  = 'pytest_runtest_setup'
        kwargs     = {'item': <Function test_keepalive[HTTP/1.0]>}
        methods    = [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/usr/lib/python3.13/vendor-packages/_pytest/run...ugin=<module '_pytest.unraisableexception' from '/usr/lib/python3.13/vendor-packages/_pytest/unraisableexception.py'>>]
        self       = <_pytest.config.PytestPluginManager object at 0x1fffe72020c590>
/usr/lib/python3.13/vendor-packages/_pytest/unraisableexception.py:90: in pytest_runtest_setup
    yield from unraisable_exception_runtest_hook()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    def unraisable_exception_runtest_hook() -> Generator[None]:
        with catch_unraisable_exception() as cm:
            try:
                yield
            finally:
                if cm.unraisable:
                    if cm.unraisable.err_msg is not None:
                        err_msg = cm.unraisable.err_msg
                    else:
                        err_msg = "Exception ignored in"
                    msg = f"{err_msg}: {cm.unraisable.object!r}\n\n"
                    msg += "".join(
                        traceback.format_exception(
                            cm.unraisable.exc_type,
                            cm.unraisable.exc_value,
                            cm.unraisable.exc_traceback,
                        )
                    )
>                   warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))
E                   pytest.PytestUnraisableExceptionWarning: Exception ignored in: <function IOBase.__del__ at 0x1fffe71f1cea20>
E                   
E                   Traceback (most recent call last):
E                     File "/usr/lib/python3.13/_pyio.py", line 418, in __del__
E                       self.close()
E                       ~~~~~~~~~~^^
E                     File "/usr/lib/python3.13/_pyio.py", line 1313, in close
E                       self.flush()
E                       ~~~~~~~~~~^^
E                     File "/usr/lib/python3.13/_pyio.py", line 1274, in flush
E                       self._flush_unlocked()
E                       ~~~~~~~~~~~~~~~~~~~~^^
E                     File "/scratch/userland-gate/components/python/cheroot/cheroot-10.0.0/cheroot/makefile.py", line 33, in _flush_unlocked
E                       n = self.raw.write(bytes(self._write_buf))
E                     File "/usr/lib/python3.13/socket.py", line 737, in write
E                       return self._sock.send(b)
E                              ~~~~~~~~~~~~~~~^^^
E                   OSError: [Errno 9] Bad file number

cm         = <_pytest.unraisableexception.catch_unraisable_exception object at 0x1fffe71f1de090>
err_msg    = 'Exception ignored in'
msg        = 'Exception ignored in: <function IOBase.__del__ at 0x1fffe71f1cea20>\n\nTraceback (most recent call last):\n  File "/u...line 737, in write\n    return self._sock.send(b)\n           ~~~~~~~~~~~~~~~^^^\nOSError: [Errno 9] Bad file number\n'
```

📋 **Environment**

 - Cheroot version: tested with 10.0.0 and 11.0.0b3
 - Python version: 3.13.0
 - OS: Oracle Solaris (but this doesn't seem to be platform dependent)

**Comment by webknjaz** [comment]
Thanks for reporting! Sounds like pytest's warning tracking feature detects an exception that was being ignored silently in older CPython releases. A short-term workaround for the tests could be adding an ignore entry to `filterwarnings` in `pytest.ini`. But long-term, we need to inspect why this is happening and track down what exactly seems to close the socket before flushing. One way to do this could be using https://docs.python.org/3/using/cmdline.html#envvar-PYTHONTRACEMALLOC.

**Comment by kulikjak** [comment]
I tried adding `PYTHONTRACEMALLOC`, but unfortunately the trace looks the same. It also passes roughly half the time I run the test suite with it, so the failure seems time dependent?

Adding `ignore::pytest.PytestUnraisableExceptionWarning` makes the test suite green.

**Comment by webknjaz** [comment]
Yeah, it sounds like there's a race condition somewhere.

If you send a PR with that but a more granular ignore matching the specific message, I'm open to accepting it as an immediate workaround.

**Comment by webknjaz** [comment]
Let's keep this open until the real fix can be implemented.

**Comment by The-Compiler** [comment]
For what it's worth, this isn't only an issue in cheroot's tests - I have a [test HTTP server](https://github.com/qutebrowser/qutebrowser/blob/main/tests/end2end/fixtures/webserver_sub.py) I run as  a subprocess for qutebrowser tests, and I see this pop up there as well.

I think a prerequisite to trigger it is that the client aborts the connection, I've been able to reproduce it when spamming F5 in a browser (which seems to have cancelled requests for e.g. `favicon.ico`), but not trivially with `curl` or `requests`.

However, setting a requests timeout seems to reproduce it nicely, here is what I use to get it happen within 0.5s or so:

```python
import time
import requests
import requests.exceptions
import threading
from cheroot import wsgi

def timeout_app(environ, start_response):
    time.sleep(0.05)
    status = '200 OK'
    headers = [('Content-type', 'text/plain; charset=utf-8')]
    start_response(status, headers)
    return [b""]

port = 1234
server = wsgi.Server(('localhost', port), timeout_app)
url = f"http://localhost:{port}"
print(url)

thread = threading.Thread(target=server.safe_start)
thread.start()

while not server.ready:
    time.sleep(0.1)

while True:
    try:
        requests.get(url, timeout=0.01)
    except requests.exceptions.ReadTimeout:
        print("!", end="", flush=True)
    else:
        print(".", end="", flush=True)
```

**Comment by The-Compiler** [comment]
Here is a workaround that works outside of pytest and hides those warnings:

```python
def unraisable_hook(unraisable: "sys.UnraisableHookArgs") -> None:
    if (
        sys.version_info[:2] == (3, 13)
        and isinstance(unraisable.exc_value, OSError)
        and unraisable.exc_value.errno == errno.EBADF
        and unraisable.object.__qualname__ == "IOBase.__del__"
    ):
        # WORKAROUND for bogus exceptions with cheroot:
        # https://github.com/cherrypy/cheroot/issues/734
        return
    sys.__unraisablehook__(unraisable)


sys.unraisablehook = unraisable_hook
```

**Comment by webknjaz** [comment]
I'm able to reproduce this with a couple of reruns of
```console
$ tox r -e py313 -qq -- -n0 --no-cov cheroot/test/test_conn.py::test_streaming_10 cheroot/test/test_conn.py::test_streaming_11 -s
```
locally.
So I've wrapped https://github.com/cherrypy/cheroot/blob/fdaa24d/cheroot/makefile.py#L32 with `try/except OSError` and put a breakpoint in there.
The actual specific exception turned out to be `ConnectionResetError` but it's logged as an `OSError` in the trace for some reason, which is confusing. I also printed out the full stack at that point:
```python
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> PDB set_trace >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
> /home/wk/src/github/cherrypy/cheroot/cheroot/makefile.py(35)_flush_unlocked()
-> breakpoint()
(Pdb) args
self = <cheroot.makefile.StreamWriter name=10>
(Pdb) pp os_exc
ConnectionResetError(104, 'Connection reset by peer')
(Pdb) pp self._write_buf
bytearray(b'2')
(Pdb) import traceback
(Pdb) traceback.print_stack()
  File "/home/wk/.pyenv/versions/3.13.0/lib/python3.13/threading.py", line 1012, in _bootstrap
    self._bootstrap_inner()
  File "/home/wk/.pyenv/versions/3.13.0/lib/python3.13/threading.py", line 1041, in _bootstrap_inner
    self.run()
  File "/home/wk/src/github/cherrypy/cheroot/cheroot/workers/threadpool.py", line 118, in run
    self._process_connections_until_interrupted()
  File "/home/wk/src/github/cherrypy/cheroot/cheroot/workers/threadpool.py", line 165, in _process_connections_until_interrupted
    keep_conn_open = conn.communicate()
  File "/home/wk/src/github/cherrypy/cheroot/cheroot/server.py", line 1317, in communicate
    req.respond()
  File "/home/wk/src/github/cherrypy/cheroot/cheroot/server.py", line 1108, in respond
    self.server.gateway(self).respond()
  File "/home/wk/src/github/cherrypy/cheroot/cheroot/wsgi.py", line 153, in respond
    self.write(chunk)
  File "/home/wk/src/github/cherrypy/cheroot/cheroot/wsgi.py", line 234, in write
    self.req.write(chunk)
  File "/home/wk/src/github/cherrypy/cheroot/cheroot/server.py", line 1164, in write
    self.conn.wfile.write(chunk)
  File "/home/wk/src/github/cherrypy/cheroot/cheroot/makefile.py", line 71, in write
    res = super().write(val, *args, **kwargs)
  File "/home/wk/src/github/cherrypy/cheroot/cheroot/makefile.py", line 23, in write
    self._flush_unlocked()
  File "/home/wk/src/github/cherrypy/cheroot/cheroot/makefile.py", line 35, in _flush_unlocked
    breakpoint()
  File "/home/wk/.pyenv/versions/3.13.0/lib/python3.13/bdb.py", line 110, in trace_dispatch
    return self.dispatch_opcode(frame, arg)
  File "/home/wk/.pyenv/versions/3.13.0/lib/python3.13/bdb.py", line 209, in dispatch_opcode
    self.user_opcode(frame)
  File "/home/wk/.pyenv/versions/3.13.0/lib/python3.13/pdb.py", line 437, in user_line
    self.interaction(frame, None)
  File "/home/wk/.pyenv/versions/3.13.0/lib/python3.13/pdb.py", line 614, in interaction
    self._cmdloop()
  File "/home/wk/.pyenv/versions/3.13.0/lib/python3.13/pdb.py", line 500, in _cmdloop
    self.cmdloop()
  File "/home/wk/.pyenv/versions/3.13.0/lib/python3.13/cmd.py", line 146, in cmdloop
    stop = self.onecmd(line)
  File "/home/wk/.pyenv/versions/3.13.0/lib/python3.13/pdb.py", line 853, in onecmd
    return cmd.Cmd.onecmd(self, line)
  File "/home/wk/.pyenv/versions/3.13.0/lib/python3.13/cmd.py", line 223, in onecmd
    return self.default(line)
  File "/home/wk/.pyenv/versions/3.13.0/lib/python3.13/pdb.py", line 761, in default
    exec(code, globals, locals)
  File "<stdin>", line 1, in <module>
```

**Comment by webknjaz** [comment]
That `ConnectionResetError` exception actually bubbles up all the way to https://github.com/cherrypy/cheroot/blob/fdaa24d/cheroot/wsgi.py#L153:
```
(Pdb) n
ConnectionResetError: [Errno 104] Connection reset by peer
> /home/wk/src/github/cherrypy/cheroot/cheroot/wsgi.py(153)respond()
-> self.write(chunk)
```
which only has try/finally and does not attempt handling it. The `finally:` block doesn't seem to attempt interacting with the socket and the exception bubbles further to https://github.com/cherrypy/cheroot/blob/fdaa24d/cheroot/server.py#L1317 where it's handled as `socket.error` (an ancient alias for `OSError`) that does nothing and eventually returns `False` meaning that the connection does not need to be kept open.

This leads to https://github.com/cherrypy/cheroot/blob/fdaa24d/cheroot/workers/threadpool.py#L215 attempting to close the connection. This `conn.close()` call is what calls `_BufferedIOMixin.close()` (on an instance of `cheroot.makefile.StreamReader` that gets this method implementation through inheritance), that in turn calls `_BufferedIOMixin.flush()` that invokes a `socket.SocketIO.flush()` (thought its `.raw` attribute which is an instance of `socket.SocketIO`) followed by a `socket.SocketIO.close()` which is fine because it doesn't attempt interacting with the closed socket. Then, server's `.close()` calls `._close_kernel_socket()` that calls `socket.shutdown(socket.SHUT_RDWR)` which internally attempts sending a TCP FIN and errors out:
```console
(Pdb) n
> /home/wk/src/github/cherrypy/cheroot/cheroot/server.py(1515)_close_kernel_socket()
-> shutdown(socket.SHUT_RDWR)  # actually send a TCP FIN
(Pdb) s
OSError: [Errno 107] Transport endpoint is not connected
> /home/wk/src/github/cherrypy/cheroot/cheroot/server.py(1515)_close_kernel_socket()
-> shutdown(socket.SHUT_RDWR)  # actually send a TCP FIN
```
After that, `socket.close()` is called w/o errors and the request handling finishes. Then, the server shuts down normally.

Once pytest printed out that 4 out of 4 tests passed, `breakpoint()` catches another exception. This time, the stream writer appears to be closed, and the control flow seems to originate in `__del__()` that we see breaking pytest runs:
```python
Results (2616.75s (0:43:36)):
       4 passed
> /home/wk/src/github/cherrypy/cheroot/cheroot/makefile.py(35)_flush_unlocked()
-> breakpoint()
(Pdb) args
self = <cheroot.makefile.StreamWriter name=-1>
(Pdb) pp os_exc
OSError(9, 'Bad file descriptor')
(Pdb) n
> /home/wk/src/github/cherrypy/cheroot/cheroot/makefile.py(36)_flush_unlocked()
-> raise
(Pdb) n
> /home/wk/src/github/cherrypy/cheroot/cheroot/makefile.py(37)_flush_unlocked()
-> except io.BlockingIOError as e:
(Pdb) n
--Return--
> /home/wk/src/github/cherrypy/cheroot/cheroot/makefile.py(37)_flush_unlocked()->None
-> except io.BlockingIOError as e:
(Pdb) n
OSError: [Errno 9] Bad file descriptor
> /home/wk/.pyenv/versions/3.13.0/lib/python3.13/_pyio.py(1274)flush()
-> self._flush_unlocked()
(Pdb) n
> /home/wk/.pyenv/versions/3.13.0/lib/python3.13/_pyio.py(1273)flush()
-> with self._write_lock:
(Pdb) n
--Return--
> /home/wk/.pyenv/versions/3.13.0/lib/python3.13/_pyio.py(1274)flush()->None
-> self._flush_unlocked()
(Pdb) n
OSError: [Errno 9] Bad file descriptor
> /home/wk/.pyenv/versions/3.13.0/lib/python3.13/_pyio.py(1313)close()
-> self.flush()
(Pdb) n
> /home/wk/.pyenv/versions/3.13.0/lib/python3.13/_pyio.py(1315)close()
-> with self._write_lock:
(Pdb) n
> /home/wk/.pyenv/versions/3.13.0/lib/python3.13/_pyio.py(1316)close()
-> self.raw.close()
(Pdb) n
> /home/wk/.pyenv/versions/3.13.0/lib/python3.13/_pyio.py(1315)close()
-> with self._write_lock:
(Pdb) n
--Return--
> /home/wk/.pyenv/versions/3.13.0/lib/python3.13/_pyio.py(1315)close()->None
-> with self._write_lock:
(Pdb) n
OSError: [Errno 9] Bad file descriptor
> /home/wk/.pyenv/versions/3.13.0/lib/python3.13/_pyio.py(418)__del__()
-> self.close()
(Pdb) n
--Return--
> /home/wk/.pyenv/versions/3.13.0/lib/python3.13/_pyio.py(418)__del__()->None
-> self.close()
(Pdb) n
--Call--
> /home/wk/src/github/cherrypy/cheroot/.tox/py313/lib/python3.13/site-packages/_pytest/unraisableexception.py(102)unraisable_hook()
-> def unraisable_hook(
```

**Comment by webknjaz** [comment]
Interestingly, if the first error (`ConnectionResetError`) does not happen, the second one doesn't either.

**Comment by webknjaz** [comment]
https://github.com/cherrypy/cheroot/commit/fd8b1e2a2662d965f05a14c2c72701decd81697c#diff-cd7dd91dba1494de1599a81e186b390a8eb9bfc73edbbad603af7b206fbefb74R920-R929 seems to be the first time this stream writer wrapper (with the `_flush_unlocked()` method) was added. On Feb 25, 2011.

Python 3.2 was released on 20 Feb, 2011. And Python 2.7 was super active back then.
The commit claims to introduce Python 3 compat, though. Not Python 2 as I'd assumed originally.

Later that year, https://github.com/python/cpython/commit/58fcf9f801d590b999401533154b63f4eb26ce6c#diff-bcdfa9cbb0764d7959cda48f9084d79785f87c5ad7460f27ba2678b0bda76e38R1120 changed expectations about the behavior of `write()`, it seems. It references https://github.com/python/cpython/issues/57531 which seems to be receiving comments even to this day.
