### ISSUE TITLE
cheroot 6.1.x  breaks cherrypy.test.webtest  14.0.1 - TerseTestResult

### ISSUE THREAD

**Issue by lsmithso** [cherrypy/cheroot#82]
cherrypy.test.webtest import fails with the latest 6.1.x cheroot.

Python 2.7.12 (default, Feb  9 2018, 15:46:55) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
> from cherrypy.test import webtest
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lsmithso/yg/panoptic_1/.tox/python/lib/python2.7/site-packages/cherrypy/test/webtest.py", line 4, in <module>
    from cheroot.test.webtest import (  # noqa
ImportError: cannot import name TerseTestResult

This works if cheroot is pinned to 6.0.0. Is this a breaking change in 6.1.x?

Thanks.

**Comment by lsmithso** [comment]
Hi: I followed your suggestion and unpinned cheroot and now it works
fine - thanks.

Sviatoslav Sydorenko writes:
 > It's kinda cleanup of old unused code. Yes, it turned out to be in a minor release, sorry. But it's not really public API. Anyway, you should import `cheroot.test.webtest` in your tests now. I think I'll pin cheroot to higher version in the next release of CherryPy.
 > 
 > -- 
 > You are receiving this because you authored the thread.
 > Reply to this email directly or view it on GitHub:
 > https://github.com/cherrypy/cheroot/issues/82#issuecomment-379934563

-- 
Les Smithson
