### ISSUE TITLE
TypeError('WSGI response header value 469 is not of type str.',)

### ISSUE THREAD

**Issue by AG3** [cherrypy/cheroot#92]
**I'm submitting a ...**
- [X] bug report
- [ ] feature request
- [ ] question about the decisions made in the repository

**Describe the bug. What is the current behavior?**

I'm using web.py and Vue.js, when it gives a response header the bug occurs. I found that was because of in the header, Content-Length field was provided in number not string. I have to look up for the standard, and the standard didn't specify the Content-Length field has to be a string.

I tried my compiled Vue page with default python http.server, it works fine. 

**What is the motivation / use case for changing the behavior?**

**To Reproduce**

1. Run '...'
2. Make request '....'
3. See error

To be honest, I'm pretty new to python web dev, I'm not sure if this is a bug or it's a mistake made by myself. Here's the log:
```python-traceback
127.0.0.1:49575 - - [06/May/2018 20:56:23] "HTTP/1.1 GET /" - 200 OK
-------------------[('Connection', 'close'), ('Content-Type', 'text/html;charset=utf-8'), ('Content-Length', 469)]
TypeError('WSGI response header value 469 is not of type str.',)
-------------------[('Connection', 'close'), ('Content-Type', 'text/html;charset=utf-8'), ('Content-Length', 469)]
-------------------[('Connection', 'close'), ('Content-Type', 'text/html;charset=utf-8'), ('Content-Length', 469)]
TypeError('WSGI response header value 469 is not of type str.',)
-------------------[('Connection', 'close'), ('Content-Type', 'text/html;charset=utf-8'), ('Content-Length', 469)]
TypeError('WSGI response header value 469 is not of type str.',)
Traceback (most recent call last):
  File "D:\Env\Python\lib\site-packages\cheroot\server.py", line 1193, in communicate
    req.respond()
  File "D:\Env\Python\lib\site-packages\cheroot\server.py", line 997, in respond
    self.server.gateway(self).respond()
  File "D:\Env\Python\lib\site-packages\cheroot\wsgi.py", line 140, in respond
    for chunk in filter(None, response):
  File "D:\Env\Python\lib\site-packages\web\httpserver.py", line 234, in __iter__
    self.start_response(self.status, self.headers)
  File "D:\Env\Python\lib\site-packages\web\httpserver.py", line 287, in xstart_response
    out = start_response(status, response_headers, *args)
  File "D:\Env\Python\lib\site-packages\cheroot\wsgi.py", line 176, in start_response
    'WSGI response header value %r is not of type str.' % v)
TypeError: WSGI response header value 469 is not of type str.
Traceback (most recent call last):
  File "D:\Env\Python\lib\site-packages\cheroot\server.py", line 1193, in communicate
    req.respond()
  File "D:\Env\Python\lib\site-packages\cheroot\server.py", line 997, in respond
    self.server.gateway(self).respond()
  File "D:\Env\Python\lib\site-packages\cheroot\wsgi.py", line 140, in respond
    for chunk in filter(None, response):
  File "D:\Env\Python\lib\site-packages\web\httpserver.py", line 234, in __iter__
    self.start_response(self.status, self.headers)
  File "D:\Env\Python\lib\site-packages\web\httpserver.py", line 287, in xstart_response
    out = start_response(status, response_headers, *args)
  File "D:\Env\Python\lib\site-packages\cheroot\wsgi.py", line 176, in start_response
    'WSGI response header value %r is not of type str.' % v)
TypeError: WSGI response header value 469 is not of type str.
TypeError('WSGI response header value 469 is not of type str.',)
Traceback (most recent call last):
  File "D:\Env\Python\lib\site-packages\cheroot\server.py", line 1193, in communicate
    req.respond()
  File "D:\Env\Python\lib\site-packages\cheroot\server.py", line 997, in respond
    self.server.gateway(self).respond()
  File "D:\Env\Python\lib\site-packages\cheroot\wsgi.py", line 140, in respond
    for chunk in filter(None, response):
  File "D:\Env\Python\lib\site-packages\web\httpserver.py", line 234, in __iter__
    self.start_response(self.status, self.headers)
  File "D:\Env\Python\lib\site-packages\web\httpserver.py", line 287, in xstart_response
    out = start_response(status, response_headers, *args)
  File "D:\Env\Python\lib\site-packages\cheroot\wsgi.py", line 176, in start_response
    'WSGI response header value %r is not of type str.' % v)
TypeError: WSGI response header value 469 is not of type str.
Traceback (most recent call last):
  File "D:\Env\Python\lib\site-packages\cheroot\server.py", line 1193, in communicate
    req.respond()
  File "D:\Env\Python\lib\site-packages\cheroot\server.py", line 997, in respond
    self.server.gateway(self).respond()
  File "D:\Env\Python\lib\site-packages\cheroot\wsgi.py", line 140, in respond
    for chunk in filter(None, response):
  File "D:\Env\Python\lib\site-packages\web\httpserver.py", line 234, in __iter__
    self.start_response(self.status, self.headers)
  File "D:\Env\Python\lib\site-packages\web\httpserver.py", line 287, in xstart_response
    out = start_response(status, response_headers, *args)
  File "D:\Env\Python\lib\site-packages\cheroot\wsgi.py", line 176, in start_response
    'WSGI response header value %r is not of type str.' % v)
TypeError: WSGI response header value 469 is not of type str.
-------------------[('Connection', 'close'), ('Content-Type', 'text/html;charset=utf-8'), ('Content-Length', 469)]
TypeError('WSGI response header value 469 is not of type str.',)
Traceback (most recent call last):
  File "D:\Env\Python\lib\site-packages\cheroot\server.py", line 1193, in communicate
    req.respond()
  File "D:\Env\Python\lib\site-packages\cheroot\server.py", line 997, in respond
    self.server.gateway(self).respond()
  File "D:\Env\Python\lib\site-packages\cheroot\wsgi.py", line 140, in respond
    for chunk in filter(None, response):
  File "D:\Env\Python\lib\site-packages\web\httpserver.py", line 234, in __iter__
    self.start_response(self.status, self.headers)
  File "D:\Env\Python\lib\site-packages\web\httpserver.py", line 287, in xstart_response
    out = start_response(status, response_headers, *args)
  File "D:\Env\Python\lib\site-packages\cheroot\wsgi.py", line 176, in start_response
    'WSGI response header value %r is not of type str.' % v)
TypeError: WSGI response header value 469 is not of type str.
-------------------[('Connection', 'close'), ('Content-Type', 'text/html;charset=utf-8'), ('Content-Length', 469)]
TypeError('WSGI response header value 469 is not of type str.',)
Traceback (most recent call last):
  File "D:\Env\Python\lib\site-packages\cheroot\server.py", line 1193, in communicate
    req.respond()
  File "D:\Env\Python\lib\site-packages\cheroot\server.py", line 997, in respond
    self.server.gateway(self).respond()
  File "D:\Env\Python\lib\site-packages\cheroot\wsgi.py", line 140, in respond
    for chunk in filter(None, response):
  File "D:\Env\Python\lib\site-packages\web\httpserver.py", line 234, in __iter__
    self.start_response(self.status, self.headers)
  File "D:\Env\Python\lib\site-packages\web\httpserver.py", line 287, in xstart_response
    out = start_response(status, response_headers, *args)
  File "D:\Env\Python\lib\site-packages\cheroot\wsgi.py", line 176, in start_response
    'WSGI response header value %r is not of type str.' % v)
TypeError: WSGI response header value 469 is not of type str.
```
Lines starting with "-----------" are my debug output.

**Expected behavior**

As I posted above.
**Details**

**Environment**

- Cheroot version: 6.2.4
- CherryPy version: X.X.X (if applicable)
- Python version: 3.6.5
- OS: Windows 10
- Browser:  Chrome 66 | Edge

**Additional context**

**Comment by AG3** [comment]
Well.... I figured out it's because I forgot to put my static files in position. However this is still weird for me, can anyone explain it a bit? Thank you!

**Comment by webknjaz** [comment]
@AG3 it looks like `web.py` framework you are using wrongly passes headers with non-string value into `start_response`. It does not depend on the header name, it is required for all kinds of headers to have string values.
I suggest you submitting an issue to `web.py` and asking them to figure it out.

**Comment by AG3** [comment]
Thank you! I’ll check wha

**Comment by AG3** [comment]
Thank you! I’ll go check what goes wrong in web.py
