### ISSUE TITLE
Extrapolating statistics from Cheroot doesn't work

### ISSUE THREAD

**Issue by sanitec** [cherrypy/cheroot#99]
**I'm submitting a ...**
- [X] bug report
- [ ] feature request
- [ ] question about the decisions made in the repository

**Describe the bug. What is the current behavior?**

Getting the following error when trying to extrapolate statistics from Cheroot:
AttributeError: 'BufferedReader' object has no attribute 'bytes_read'

**What is the motivation / use case for changing the behavior?**
It's broken

**To Reproduce**

1. Configure Cherrypy to use the following plugin:

```python
import logging

import cherrypy

class CherootStatistics(cherrypy.process.plugins.SimplePlugin):
    def __init__(self, bus):
        super(CherootStatistics, self).__init__(bus)
        self._enabled = False

    def main(self):
        if not self._enabled:
            self.bus.log('Enabling Cheroot statistics')
            for key in logging.statistics.keys():
                if 'Cheroot HTTPServer' in key:
                    logging.statistics[key]['Enabled'] = True
                    break
            self._enabled = True
```
2.  Mount cpstats to '/cpstats'
3.  Open localhost:8080/cpstats in browser

**Expected behavior**

To see the beautiful statistics of Cheroot

**Details**

```python-traceback
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/cherrypy/_cprequest.py", line 631, in respond
    self._do_respond(path_info)
  File "/usr/local/lib/python3.6/site-packages/cherrypy/_cprequest.py", line 690, in _do_respond
    response.body = self.handler()
  File "/usr/local/lib/python3.6/site-packages/cherrypy/lib/encoding.py", line 264, in __call__
    ct.params['charset'] = self.find_acceptable_charset()
  File "/usr/local/lib/python3.6/site-packages/cherrypy/lib/encoding.py", line 173, in find_acceptable_charset
    if encoder(self.default_encoding):
  File "/usr/local/lib/python3.6/site-packages/cherrypy/lib/encoding.py", line 114, in encode_string
    for chunk in self.body:
  File "/usr/local/lib/python3.6/site-packages/cherrypy/lib/cpstats.py", line 522, in index
    for title, scalars, collections in self.get_namespaces():
  File "/usr/local/lib/python3.6/site-packages/cherrypy/lib/cpstats.py", line 587, in get_namespaces
    s = extrapolate_statistics(logging.statistics)
  File "/usr/local/lib/python3.6/site-packages/cherrypy/lib/cpstats.py", line 212, in extrapolate_statistics
    v = extrapolate_statistics(v)
  File "/usr/local/lib/python3.6/site-packages/cherrypy/lib/cpstats.py", line 216, in extrapolate_statistics
    v = v(scope)
  File "/usr/local/lib/python3.6/site-packages/cheroot/server.py", line 1529, in <lambda>
    [w['Bytes Read'](w) for w in s['Worker Threads'].values()], 0),
  File "/usr/local/lib/python3.6/site-packages/cheroot/server.py", line 1529, in <listcomp>
    [w['Bytes Read'](w) for w in s['Worker Threads'].values()], 0),
  File "/usr/local/lib/python3.6/site-packages/cheroot/workers/threadpool.py", line 76, in <lambda>
    self.conn.rfile.bytes_read
AttributeError: 'BufferedReader' object has no attribute 'bytes_read'
```

**Environment**

- Cheroot version: 6.3.1
- CherryPy version: 15.0.0 (if applicable)
- Python version: 3.6.5
- OS: MacOS 10.13.x

**Additional context**

**Comment by webknjaz** [comment]
@sanitec do you have cheroot+cherrypy version combination when it worked?

**Comment by sanitec** [comment]
@webknjaz  No, we've only tried with latest versions. It's a feature we're keen to use in our application, but haven't had much luck with Cheroot's statistics.

**Comment by webknjaz** [comment]
It looks like this argument is used to be present in Python 2 implementation, while Python 3 returns  BufferedReader from stdlib, which doesn't have this attribute implemented: https://github.com/cherrypy/cheroot/blob/ad4cd1cecb935539413db8b59071cb8c3fed4e8f/cheroot/makefile.py#L91

**Comment by webknjaz** [comment]
cc @jaraco we probably need to refactor `cheroot.makefile` module

**Comment by jshiell** [comment]
I fear I'm still seeing this issue with Cheroot 6.5.4 on Python 3.6.8 and having to monkey-patch `WorkerThread.run` to avoid 
```
self.bytes_read += self.conn.rfile.bytes_read
self.bytes_written += self.conn.wfile.bytes_written
```

**Comment by webknjaz** [comment]
This commit https://github.com/cherrypy/cheroot/pull/176/commits/14bcf2a5c1034e23fddc621616b68f66d04d20be should probably be cherry-picked to address the current issue...

**Comment by jaraco** [comment]
I could use some help with this issue. Namely, how to replicate it. Instructions say "configure plugin" and "mount cpstats", but I'm not sure how the user might have done that. I could try to figure it out, but it would be nice to have a full reproducer that doesn't require me to make assumptions or code the reproducer.

**Comment by jaraco** [comment]
I created [this script](https://gist.github.com/jaraco/b67d91b555768bbd7c4001bdc978ce6a) to reproduce the issue. I also created the following Dockerfile that will build a server:

```
FROM python:3

RUN pip install cherrypy

ADD https://gist.githubusercontent.com/jaraco/b67d91b555768bbd7c4001bdc978ce6a/raw/f39d4a95905d69882a3b18fc5209e847f9ee775a/server.py server.py

EXPOSE 8080

CMD python server.py
```

Just create `Dockerfile` and then build with `docker build . -t cheroot99`. Then `docker run -p 8080:8080 -it cheroot99`. It will launch a server on port 8080. Then, requesting the root page, you get the statistics:

```
$ http http://localhost:8080                                                                                                                                                 
HTTP/1.1 200 OK
Content-Length: 6858
Content-Type: text/html;charset=utf-8
Date: Tue, 26 Mar 2019 20:20:40 GMT
Server: CherryPy/18.1.0

<html>
<head>
    <title>Statistics</title>
<style>

th, td {
    padding: 0.25em 0.5em;
    border: 1px solid #666699;
}

table {
    border-collapse: collapse;
}

table.stats1 {
    width: 100%;
}

table.stats1 th {
    font-weight: bold;
    text-align: right;
    background-color: #CCD5DD;
}

table.stats2, h2 {
    margin-left: 50px;
}

table.stats2 th {
    font-weight: bold;
    text-align: center;
    background-color: #CCD5DD;
}

</style>
</head>
<body>

<h1>Cheroot HTTPServer 139801399372208</h1>

<table class='stats1'>
    <tbody>

        <tr>
            <th>Accepts</th><td id='Cheroot HTTPServer 139801399372208-Accepts'>0</td>
            <th>Accepts/sec</th><td id='Cheroot HTTPServer 139801399372208-Accepts/sec'>0.0</td>
            <th>Bind Address</th><td id='Cheroot HTTPServer 139801399372208-Bind Address'>('::', 8080)</td>
        </tr>
        <tr>
            <th>Bytes Read</th><td id='Cheroot HTTPServer 139801399372208-Bytes Read'>-1</td>
            <th>Bytes Written</th><td id='Cheroot HTTPServer 139801399372208-Bytes Written'>-1</td>
            <th>Enabled</th><td id='Cheroot HTTPServer 139801399372208-Enabled'>False</td>
        </tr>
        <tr>
            <th>Queue</th><td id='Cheroot HTTPServer 139801399372208-Queue'>0</td>
            <th>Read Throughput</th><td id='Cheroot HTTPServer 139801399372208-Read Throughput'>-1</td>
            <th>Requests</th><td id='Cheroot HTTPServer 139801399372208-Requests'>-1</td>
        </tr>
        <tr>
            <th>Run time</th><td id='Cheroot HTTPServer 139801399372208-Run time'>-1</td>
            <th>Socket Errors</th><td id='Cheroot HTTPServer 139801399372208-Socket Errors'>0</td>
            <th>Threads</th><td id='Cheroot HTTPServer 139801399372208-Threads'>10</td>
        </tr>
        <tr>
            <th>Threads Idle</th><td id='Cheroot HTTPServer 139801399372208-Threads Idle'>9</td>
            <th>Work Time</th><td id='Cheroot HTTPServer 139801399372208-Work Time'>-1</td>
            <th>Write Throughput</th><td id='Cheroot HTTPServer 139801399372208-Write Throughput'>-1</td>
        </tr>
    </tbody>
</table>
<h2>Worker Threads</h2>
<table class='stats2'>
    <thead>
        <tr>
            <th>ID</th>
            <th>Bytes Read</th>
            <th>Bytes Written</th>
            <th>Read Throughput</th>
            <th>Requests</th>
            <th>Work Time</th>
            <th>Write Throughput</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>CP Server Thread-10</td>
            <td>0</td>
            <td>0</td>
            <td>0.0</td>
            <td>0</td>
            <td>0</td>
            <td>0.0</td>
        </tr>
        <tr>
            <td>CP Server Thread-11</td>
            <td>0</td>
            <td>0</td>
            <td>0.0</td>
            <td>0</td>
            <td>0</td>
            <td>0.0</td>
        </tr>
        <tr>
            <td>CP Server Thread-12</td>
            <td>0</td>
            <td>0</td>
            <td>0.0</td>
            <td>0</td>
            <td>0</td>
            <td>0.0</td>
        </tr>
        <tr>
            <td>CP Server Thread-3</td>
            <td>0</td>
            <td>0</td>
            <td>0.0</td>
            <td>0</td>
            <td>0</td>
            <td>0.0</td>
        </tr>
        <tr>
            <td>CP Server Thread-4</td>
            <td>0</td>
            <td>0</td>
            <td>0.0</td>
            <td>0</td>
            <td>0</td>
            <td>0.0</td>
        </tr>
        <tr>
            <td>CP Server Thread-5</td>
            <td>0</td>
            <td>0</td>
            <td>0.0</td>
            <td>0</td>
            <td>0</td>
            <td>0.0</td>
        </tr>
        <tr>
            <td>CP Server Thread-6</td>
            <td>0</td>
            <td>0</td>
            <td>0.0</td>
            <td>0</td>
            <td>0</td>
            <td>0.0</td>
        </tr>
        <tr>
            <td>CP Server Thread-7</td>
            <td>0</td>
            <td>0</td>
            <td>0.0</td>
            <td>0</td>
            <td>0</td>
            <td>0.0</td>
        </tr>
        <tr>
            <td>CP Server Thread-8</td>
            <td>0</td>
            <td>0</td>
            <td>0.0</td>
            <td>0</td>
            <td>0</td>
            <td>0.0</td>
        </tr>
        <tr>
            <td>CP Server Thread-9</td>
            <td>0</td>
            <td>0</td>
            <td>0.0</td>
            <td>0</td>
            <td>0</td>
            <td>0.0</td>
        </tr>
    </tbody>
</table>
<h1>CherryPy Applications</h1>

<table class='stats1'>
    <tbody>

        <tr>
            <th>Bytes Read/Request</th><td id='CherryPy Applications-Bytes Read/Request'>0.000</td>
            <th>Bytes Read/Second</th><td id='CherryPy Applications-Bytes Read/Second'>0.000</td>
            <th>Bytes Written/Request</th><td id='CherryPy Applications-Bytes Written/Request'>0.000</td>
        </tr>
        <tr>
            <th>Bytes Written/Second</th><td id='CherryPy Applications-Bytes Written/Second'>0.000</td>
            <th>Current Requests</th><td id='CherryPy Applications-Current Requests'>0</td>
            <th>Current Time</th><td id='CherryPy Applications-Current Time'>2019-03-26 20:20:40</td>
        </tr>
        <tr>
            <th>Enabled</th><td id='CherryPy Applications-Enabled'>
            <form action="pause" method="POST" style="display:inline">
            <input type="hidden" name="namespace" value="CherryPy Applications" />
            <input type="submit" value="Pause" />
            </form>
            <form action="resume" method="POST" style="display:inline">
            <input type="hidden" name="namespace" value="CherryPy Applications" />
            <input type="submit" value="Resume" disabled="disabled" />
            </form>
            </td>
            <th>Requests/Second</th><td id='CherryPy Applications-Requests/Second'>0.000</td>
            <th>Server Version</th><td id='CherryPy Applications-Server Version'>18.1.0</td>
        </tr>
        <tr>
            <th>Start Time</th><td id='CherryPy Applications-Start Time'>2019-03-26 20:20:33</td>
            <th>Total Bytes Read</th><td id='CherryPy Applications-Total Bytes Read'>0</td>
            <th>Total Bytes Written</th><td id='CherryPy Applications-Total Bytes Written'>0</td>
        </tr>
        <tr>
            <th>Total Requests</th><td id='CherryPy Applications-Total Requests'>0</td>
            <th>Total Time</th><td id='CherryPy Applications-Total Time'>0.000</td>
            <th>Uptime</th><td id='CherryPy Applications-Uptime'>7.203</td>
        </tr>
    </tbody>
</table>
<h2>Requests</h2>
<table class='stats2'>
    <thead>
        <tr>
            <th>ID</th>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>
</body>
</html>
```

Everything seems to be working. I seem to be unable to replicate the issue with the latest cherrypy/cheroot.

**Comment by jaraco** [comment]
Hmm. Earlier when I was running the server, I saw the "Enabling Cheroot statistics", which I no longer see, so I don't think the plugin is being activated.

**Comment by jaraco** [comment]
I only sometimes see the message "Enabling Cheroot statistics" and seemingly only when the Autoreloader is triggered and after the engine exits:

```
[26/Mar/2019:16:45:01] ENGINE Listening for SIGTERM.
[26/Mar/2019:16:45:01] ENGINE Listening for SIGHUP.
[26/Mar/2019:16:45:01] ENGINE Listening for SIGUSR1.
[26/Mar/2019:16:45:01] ENGINE Bus STARTING
[26/Mar/2019:16:45:01] ENGINE Started monitor thread 'Autoreloader'.
[26/Mar/2019:16:45:01] ENGINE Serving on http://::0:8080
[26/Mar/2019:16:45:01] ENGINE Bus STARTED
[26/Mar/2019:16:45:03] ENGINE Restarting because /Users/jaraco/code/public/cherrypy/cheroot/server.py changed.
[26/Mar/2019:16:45:03] ENGINE Stopped thread 'Autoreloader'.
[26/Mar/2019:16:45:03] ENGINE Bus STOPPING
[26/Mar/2019:16:45:03] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('::', 8080)) shut down
[26/Mar/2019:16:45:03] ENGINE Bus STOPPED
[26/Mar/2019:16:45:03] ENGINE Bus EXITING
[26/Mar/2019:16:45:03] ENGINE Bus EXITED
[26/Mar/2019:16:45:03] ENGINE Enabling Cheroot statistics
[26/Mar/2019:16:45:03] ENGINE Waiting for child threads to terminate...
[26/Mar/2019:16:45:03] ENGINE Re-spawning /Library/Frameworks/Python.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python server.py
[26/Mar/2019:16:45:04] ENGINE Listening for SIGTERM.
[26/Mar/2019:16:45:04] ENGINE Listening for SIGHUP.
[26/Mar/2019:16:45:04] ENGINE Listening for SIGUSR1.
[26/Mar/2019:16:45:04] ENGINE Bus STARTING
[26/Mar/2019:16:45:04] ENGINE Started monitor thread 'Autoreloader'.
[26/Mar/2019:16:45:04] ENGINE Serving on http://::0:8080
[26/Mar/2019:16:45:04] ENGINE Bus STARTED
```

**Comment by jaraco** [comment]
Okay, if I grab cherrypy 15.0.0, I see the cheroot statistics get enabled and the 'main' event fires several times per second... so something about cherrypy 18.0.1 has eliminated that main event firing.

**Comment by jaraco** [comment]
Aha, so the issue appears to be in cherrypy/cherrypy@20bc9dbf617c61b8c2b7e847d3b88caeabfd6528. Without that, `main` only gets called when the state changes, instead of periodically as the docs state it should.

**Comment by jaraco** [comment]
After addressing the emergent issue in CherryPy, I've had some success reproducing the issue with [this script](https://gist.github.com/a7508147a72aa23e0936adbdc1395743) (use [this link in the Dockerfile](https://gist.githubusercontent.com/jaraco/a7508147a72aa23e0936adbdc1395743/raw/0b6f381b3e9d921af7adc65fd97af9b07e665e9c/foo.py)). Now, when I request `/` against that server, I see this in the server output:

```
[27/Mar/2019:09:56:49] ENGINE Listening for SIGTERM.
[27/Mar/2019:09:56:49] ENGINE Listening for SIGHUP.
[27/Mar/2019:09:56:49] ENGINE Listening for SIGUSR1.
[27/Mar/2019:09:56:49] ENGINE Bus STARTING
[27/Mar/2019:09:56:49] ENGINE Started monitor thread 'Autoreloader'.
[27/Mar/2019:09:56:49] ENGINE Serving on http://::0:8080
[27/Mar/2019:09:56:49] ENGINE Bus STARTED
[27/Mar/2019:09:56:49] ENGINE Enabling Cheroot HTTPServer 4478267576 statistics
Exception in thread CP Server Thread-4:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/Users/jaraco/code/public/cherrypy/cheroot/cheroot/workers/threadpool.py", line 119, in run
    self.bytes_read += self.conn.rfile.bytes_read
AttributeError: 'StreamReader' object has no attribute 'bytes_read'

::1 - - [27/Mar/2019:09:56:58] "GET / HTTP/1.1" 200 11 "" "HTTPie/1.0.2"
```

**Comment by jaraco** [comment]
I've updated the [script to support Python 2.7 also](https://gist.github.com/jaraco/a7508147a72aa23e0936adbdc1395743) and was able to confirm the issue only exists on Python 3.
